- Makefile
- internal/controller/suite_test.go
- internal/controller/template_controller.go
- internal/controller/template_controller_test.go
Also, consider template type from spec as well.
HMC-108
> Validate Templates with external source

- .github/workflows/test.yml
> Remove config dir from paths-ignore

- README.md
- docs/templates/main.md
> Document Template system

- templates/aws-hosted-cp/Chart.yaml
- templates/aws-hosted-cp/values.yaml
- templates/aws-standalone-cp/Chart.yaml
- templates/aws-standalone-cp/values.yaml
- templates/hmc-templates/files/templates/aws-hosted-cp.yaml
- templates/hmc-templates/files/templates/aws-standalone-cp.yaml
> Update k0s version to v1.30.2+k0s.0

- README.md
- docs/aws/hosted-control-plane.md
HMC-106
Additional docs for hosted-cp scenario.
> Add docs on aws-hosted-cp temlate

- internal/webhook/management_webhook.go
> Forbid Management removal if Deployments exist

- api/v1alpha1/management_types.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
> Split Management reconcile into Update and Delete

- Makefile
> Reuse last HMC values on dev-apply

- docs/templates/main.md
- templates/hmc/values.yaml
> Watch only hmc-managed resources in source-controller

- api/v1alpha1/deployment_types.go
- api/v1alpha1/management_types.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/helm/release.go
- internal/utils/kube.go
> Remove associated helm releases when Management deletion is requested 

- templates/aws-hosted-cp/values.yaml
- templates/aws-standalone-cp/values.yaml
> Fix permissions for worker nodes

- README.md
> Add HMC cleanup docs

- docs/aws/cluster-parameters.md
- templates/aws-hosted-cp/templates/awsmachinetemplate.yaml
- templates/aws-hosted-cp/templates/machinedeployment.yaml
- templates/aws-hosted-cp/values.schema.json
- templates/aws-hosted-cp/values.yaml
- templates/aws-standalone-cp/templates/awsmachinetemplate-controlplane.yaml
- templates/aws-standalone-cp/templates/awsmachinetemplate-worker.yaml
- templates/aws-standalone-cp/templates/machinedeployment.yaml
- templates/aws-standalone-cp/values.schema.json
- templates/aws-standalone-cp/values.yaml
> Automatic AMI lookup parameters

- docs/azure/hosted-control-plane.md
- templates/azure-hosted-cp/.helmignore
- templates/azure-hosted-cp/Chart.yaml
- templates/azure-hosted-cp/templates/_helpers.tpl
- templates/azure-hosted-cp/templates/azurecluster.yaml
- templates/azure-hosted-cp/templates/azuremachinetemplate.yaml
- templates/azure-hosted-cp/templates/cluster.yaml
- templates/azure-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/azure-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/azure-hosted-cp/templates/machinedeployment.yaml
- templates/azure-hosted-cp/values.schema.json
- templates/azure-hosted-cp/values.yaml
- templates/hmc-templates/files/templates/azure-hosted-cp.yaml
> Add Azure hosted CP template

- README.md
- docs/azure/machine-parameters.md
- docs/azure/main.md
> Add Azure template docs

- Makefile
- config/dev/aws-deployment.yaml
- config/dev/azure-credentials.yaml
- config/dev/azure-deployment.yaml
- docs/dev.md
> Add azure related make targets

- README.md
- api/v1alpha1/management_types.go
- internal/controller/deployment_controller.go
- internal/controller/deployment_controller_test.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/telemetry/tracker.go
- internal/webhook/managedcluster_webhook.go
- templates/hmc/templates/crds/hmc.mirantis.com_managements.yaml
- test/objects/management/management.go
> Make Management object cluster-scoped

- api/v1alpha1/management_types.go
- api/v1alpha1/template_types.go
- cmd/main.go
- internal/controller/managedcluster_controller.go
- internal/controller/managedcluster_controller_test.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/controller/suite_test.go
- internal/telemetry/tracker.go
- internal/utils/kube.go
- internal/webhook/managedcluster_webhook.go
- internal/webhook/managedcluster_webhook_test.go
- templates/hmc/values.yaml
> Remove dependency on hmc-system namespace

- Makefile
Fixes azure DEV_PROVIDER deployment config
> Fix dev-provider-apply managedcluster file name in Makefile

- templates/cluster/vsphere-hosted-cp/.helmignore
- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/templates/_helpers.tpl
- templates/cluster/vsphere-hosted-cp/templates/cluster.yaml
- templates/cluster/vsphere-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/vsphere-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/vsphere-hosted-cp/templates/machinedeployment.yaml
- templates/cluster/vsphere-hosted-cp/templates/vspherecluster.yaml
- templates/cluster/vsphere-hosted-cp/templates/vspheremachinetemplate.yaml
- templates/cluster/vsphere-hosted-cp/values.schema.json
- templates/cluster/vsphere-hosted-cp/values.yaml
- templates/provider/hmc-templates/files/templates/vsphere-hosted-cp.yaml
> Add vSphere hosted CP template

- templates/cluster/vsphere-standalone-cp/.helmignore
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/templates/_helpers.tpl
- templates/cluster/vsphere-standalone-cp/templates/cluster.yaml
- templates/cluster/vsphere-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/vsphere-standalone-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/vsphere-standalone-cp/templates/machinedeployment.yaml
- templates/cluster/vsphere-standalone-cp/templates/vspherecluster.yaml
- templates/cluster/vsphere-standalone-cp/templates/vspheremachinetemplate-controlplane.yaml
- templates/cluster/vsphere-standalone-cp/templates/vspheremachinetemplate-worker.yaml
- templates/cluster/vsphere-standalone-cp/values.schema.json
- templates/cluster/vsphere-standalone-cp/values.yaml
- templates/provider/hmc-templates/files/templates/vsphere-standalone-cp.yaml
> Add vsphere standalone CP template

- README.md
- docs/vsphere/cluster-parameters.md
- docs/vsphere/hosted-control-plane.md
- docs/vsphere/machine-parameters.md
- docs/vsphere/main.md
> Add vsphere provider docs

- .github/workflows/test.yml
> Skip cleanup job when e2e tests are skipped

- api/v1alpha1/clustertemplate_types.go
- api/v1alpha1/providertemplate_types.go
- api/v1alpha1/servicetemplate_types.go
- templates/provider/hmc/templates/crds/hmc.mirantis.com_clustertemplates.yaml
- templates/provider/hmc/templates/crds/hmc.mirantis.com_providertemplates.yaml
- templates/provider/hmc/templates/crds/hmc.mirantis.com_servicetemplates.yaml
> Validate that Templates spec is immutable

- cmd/main.go
- internal/controller/managedcluster_controller.go
- internal/controller/managedcluster_controller_test.go
- internal/controller/suite_test.go
- internal/webhook/managedcluster_webhook.go
- internal/webhook/managedcluster_webhook_test.go
- internal/webhook/template_webhook.go
- internal/webhook/template_webhook_test.go
- test/objects/template/template.go
> Support to reference ClusterTemplate from the ManagedClusters' namespace only

- api/v1alpha1/templatechain_types.go
- cmd/main.go
- internal/controller/suite_test.go
- internal/webhook/templatechain_webhook.go
- internal/webhook/templatechain_webhook_test.go
- templates/provider/hmc/templates/crds/hmc.mirantis.com_clustertemplatechains.yaml
- templates/provider/hmc/templates/crds/hmc.mirantis.com_servicetemplatechains.yaml
- templates/provider/hmc/templates/webhooks.yaml
> Validate TemplateChains

- api/v1alpha1/credential_types.go
- cmd/main.go
- internal/controller/credential_controller.go
- internal/controller/managedcluster_controller.go
- internal/controller/managedcluster_controller_test.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/controller/templatemanagement_controller.go
- internal/controller/templatemanagement_controller_test.go
- internal/telemetry/client.go
- internal/telemetry/event.go
- internal/telemetry/tracker.go
- internal/templateutil/state.go
- internal/webhook/managedcluster_webhook.go
- templates/provider/hmc/templates/crds/hmc.mirantis.com_credentials.yaml
- test/scheme/scheme.go
* removed/unexported a couple of variables being not used as exported
* decreased cognitive burden removing redundant fields/smell patterns
* a couple of comments to reflect on the public API
> Chores with human linter

- templates/cluster/aws-hosted-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/Chart.yaml
> Fix CP providers label in charts meta

- cmd/main.go
- hack/templates.sh
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/utils/release.go
- internal/utils/release_test.go
- templates/provider/hmc-templates/files/templates/aws-hosted-cp.yaml
- templates/provider/hmc-templates/files/templates/aws-standalone-cp.yaml
- templates/provider/hmc-templates/files/templates/azure-hosted-cp.yaml
- templates/provider/hmc-templates/files/templates/azure-standalone-cp.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-aws.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-azure.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-vsphere.yaml
- templates/provider/hmc-templates/files/templates/cluster-api.yaml
- templates/provider/hmc-templates/files/templates/hmc.yaml
- templates/provider/hmc-templates/files/templates/ingress-nginx.yaml
- templates/provider/hmc-templates/files/templates/k0smotron.yaml
- templates/provider/hmc-templates/files/templates/kyverno.yaml
- templates/provider/hmc-templates/files/templates/projectsveltos.yaml
- templates/provider/hmc-templates/files/templates/vsphere-hosted-cp.yaml
- templates/provider/hmc-templates/files/templates/vsphere-standalone-cp.yaml
- templates/provider/hmc-templates/templates/templates.yaml
> Preload Templates associated with Release objects

- cmd/main.go
- config/dev/hmc_values.yaml
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/webhook/management_webhook.go
- internal/webhook/management_webhook_test.go
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/values.yaml
- templates/provider/hmc/templates/deployment.yaml
- templates/provider/hmc/values.yaml
> Permanently disable init parameters after bootstrap

- cmd/main.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/helm/repo.go
> Create HelmRepository during the initial HMC installation

- cmd/main.go
- config/dev/hmc_values.yaml
- internal/controller/release_controller.go
- templates/provider/hmc/templates/deployment.yaml
- templates/provider/hmc/values.yaml
> Add a separate flag to skip Templates creation in Release controller

- internal/controller/release_controller.go
- internal/utils/release.go
> Fix collision in hmc and hmc-templates chart names

- api/v1alpha1/managedcluster_types.go
- templates/provider/hmc/templates/crds/hmc.mirantis.com_managedclusters.yaml
Resolves #364 
Small fix to get rid of `Deployment` resource legacy.
> Change ManagedCluster's short names

- internal/controller/management_controller.go
> Reflect associated template in the component status

- internal/controller/templatechain_controller.go
- internal/controller/templatechain_controller_test.go
Now the chart name contains the chart version. Also, fixed error handling and adapted testing accordingly.
> Fix chartRef for delivered Templates

- .github/workflows/release.yml
> Publish Release object to gh release assets

- templates/provider/k0smotron/templates/providers.yaml
> K0smotron capi official provider

- Makefile
- templates/provider/hmc-templates/files/release.yaml
> Strip leading v in VERSION

- templates/provider/hmc-templates/files/release.yaml
> Fix sveltos tpls version in the Release

- config/dev/aws-managedcluster.yaml
- config/dev/azure-managedcluster.yaml
- config/dev/eks-managedcluster.yaml
- config/dev/vsphere-managedcluster.yaml
- templates/cluster/aws-hosted-cp/Chart.yaml
- templates/cluster/aws-hosted-cp/values.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/values.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/values.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/values.yaml
- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/values.yaml
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/values.yaml
- templates/provider/hmc-templates/files/templates/aws-hosted-cp-0-0-2.yaml
- templates/provider/hmc-templates/files/templates/aws-standalone-cp-0-0-2.yaml
- templates/provider/hmc-templates/files/templates/azure-hosted-cp-0-0-2.yaml
- templates/provider/hmc-templates/files/templates/azure-standalone-cp-0-0-2.yaml
- templates/provider/hmc-templates/files/templates/vsphere-hosted-cp-0-0-2.yaml
- templates/provider/hmc-templates/files/templates/vsphere-standalone-cp-0-0-2.yaml
- test/e2e/managedcluster/resources/aws-hosted-cp.yaml.tpl
- test/e2e/managedcluster/resources/aws-standalone-cp.yaml.tpl
- test/e2e/managedcluster/resources/azure-hosted-cp.yaml.tpl
- test/e2e/managedcluster/resources/azure-standalone-cp.yaml.tpl
- test/e2e/managedcluster/resources/vsphere-hosted-cp.yaml.tpl
- test/e2e/managedcluster/resources/vsphere-standalone-cp.yaml.tpl
> Update k0s version to 1.31.1+k0s.1

- config/dev/azure-managedcluster.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/templates/k0scontrolplane.yaml
- templates/provider/hmc-templates/files/templates/azure-hosted-cp-0-0-3.yaml
- templates/provider/hmc-templates/files/templates/azure-standalone-cp-0-0-3.yaml
Fix the issue with CCM installation on Azure by using copy of the chart in our helm repo
> Set forked cloud-provider-azure chart for Azure templates

- templates/cluster/aws-eks/Chart.yaml
- templates/provider/hmc-templates/files/templates/aws-eks-0-0-2.yaml
All charts versions were updated but EKS. This PR fixes EKS chart version inconsistency.
> Updated EKS chart version

- README.md
- config/dev/aws-credentials.yaml
- config/dev/aws-managedcluster.yaml
- config/dev/azure-credentials.yaml
- config/dev/eks-managedcluster.yaml
- config/dev/vsphere-credentials.yaml
- config/dev/vsphere-managedcluster.yaml
Dev configs had a lot of old stuff in them (especially AWS) which obsolete now and clog everything.
Some README changes to make recent credential changes and versioning more visible
> Fixes in dev configs and README to reflect recent API changes

- internal/webhook/management_webhook.go
- internal/webhook/management_webhook_test.go
* provider tpl capi contract should not support all of the declared capi contracts
Fixes #586
> Fix incorrect comp sets check in admission

- .golangci.yml
- api/v1alpha1/clustertemplate_types.go
- api/v1alpha1/providertemplate_types.go
- internal/controller/managedcluster_controller.go
- internal/controller/management_controller.go
- internal/controller/template_controller.go
- internal/controller/templatechain_controller.go
- internal/controller/templatechain_controller_test.go
- internal/credspropagation/azure.go
- internal/credspropagation/vsphere.go
- internal/webhook/managedcluster_webhook.go
- internal/webhook/management_webhook.go
- internal/webhook/templatemanagement_webhook.go
- test/e2e/managedcluster/clusteridentity/clusteridentity.go
* set explicit linter rules for revive and govet
* granular exclusions for govet/revive
* removed unused exclusions
* added several extra linters
> Explicit linter rules

- templates/provider/cluster-api/Chart.yaml
- templates/provider/cluster-api/templates/provider.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api.yaml
> Update core capi to v1.8.5

- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/k0smotron.yaml
- templates/provider/k0smotron/Chart.yaml
- templates/provider/k0smotron/templates/providers.yaml
> Bump k0smotron to v1.2.0

- templates/provider/hmc/templates/rbac/user-facing/secrets-viewer.yaml
> Add secrets viewer role to get kubeconfigs

- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/projectsveltos.yaml
- templates/provider/projectsveltos/Chart.lock
- templates/provider/projectsveltos/Chart.yaml
> Bumpt sveltos to 0.42.0

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/cluster-api-provider-azure/templates/provider.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-azure.yaml
> Bump azure provider to v1.17.1

- templates/provider/cluster-api-provider-aws/Chart.yaml
- templates/provider/cluster-api-provider-aws/templates/provider.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-aws.yaml
> Bump aws provider to v2.7.1

- templates/provider/hmc-templates/files/release.yaml
> Set 0.0.4 version in the Release object

- README.md
Minor misprint fix in README.md (plate->plane)
> Minor misprint fix in README.md

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/cluster-api-provider-azure/templates/provider.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-azure.yaml
> Bump azure provider to v1.17.2

- api/v1alpha1/indexers.go
- api/v1alpha1/release_types.go
- internal/controller/release_controller.go
Validate that all ProviderTemplates are created and valid before marking Release as Ready
Resolves #397
> Validate Release object

- internal/controller/multiclusterservice_controller.go
- internal/sveltos/status.go
- internal/sveltos/status_test.go
as discussed in https://github.com/Mirantis/hmc/pull/673#discussion_r1858055811
> Rename SetStatusConditions to GetStatusConditions

- internal/webhook/management_webhook.go
- internal/webhook/management_webhook_test.go
- test/objects/release/release.go
> Validate Management creation/update with Release

- PROJECT
- api/v1alpha1/management_types.go
- cmd/main.go
- internal/webhook/release_webhook.go
- internal/webhook/release_webhook_test.go
- templates/provider/hmc/templates/webhooks.yaml
- test/objects/release/release.go
> Validate Release object removal

- internal/controller/managedcluster_controller.go
- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
* add helm-release label to the helmreleases installed by the HMC management part
* cleanup helmreleases only if removed and the new label value equals to the mgmt part
* small refactor to fix linter
Closes #703
> Fix components cleanup

- internal/controller/templatechain_controller.go
- internal/controller/templatechain_controller_test.go
> Fix missing spec fields in distributed templates

- templates/provider/hmc/Chart.lock
- templates/provider/hmc/Chart.yaml
> Update capi-operator to v0.15.1

- .github/workflows/build_test.yml
- Dockerfile
- go.mod
> Bump go to 1.23

- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/k0smotron.yaml
- templates/provider/k0smotron/Chart.yaml
- templates/provider/k0smotron/templates/providers.yaml
> Bump k0smotron to v1.3.0

- templates/provider/cluster-api-provider-vsphere/Chart.yaml
- templates/provider/cluster-api-provider-vsphere/templates/provider.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-vsphere.yaml
> Bump vsphere version to v1.12.0

- Makefile
- docs/dev.md
- fix comments to include some items to "make help" output
- add useful "make help" instruction to docs/dev.md
> Makefile: fixes and improvements

- README.md
- templates/provider/kcm-templates/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
> Update templates for v0.0.7

- internal/controller/templatechain_controller.go
- internal/controller/templatechain_controller_test.go
> Only distribute templates that are managed by KCM template chains

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> Bump cert-manager to v1.16.3

- templates/provider/cluster-api/Chart.yaml
- templates/provider/cluster-api/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api.yaml
> Bump capi to v1.9.4

- internal/controller/management_controller.go
> Fix initial templates helm release removal

- templates/provider/k0smotron/Chart.yaml
- templates/provider/k0smotron/templates/providers.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/k0smotron.yaml
> Bump k0smotron to v1.4.0

- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/cluster-api-provider-openstack/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
> Bump openstack provider to v0.11.4

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/cluster-api-provider-azure/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-azure.yaml
> Bump azure provider to v1.18.0

- Makefile
- config/dev/adopted-clusterdeployment.yaml
- config/dev/aks-clusterdeployment.yaml
- config/dev/aws-clusterdeployment.yaml
- config/dev/azure-clusterdeployment.yaml
- config/dev/eks-clusterdeployment.yaml
- config/dev/openstack-clusterdeployment.yaml
- config/dev/vsphere-clusterdeployment.yaml
- internal/controller/clusterdeployment_controller.go
- internal/providers/providers.go
- internal/providers/yaml.go
- providers/aws.yml
- providers/azure.yml
- providers/openstack.yml
- providers/vsphere.yml
PR extend providers interface to support multiple cluster GVKs and improves Dev-experience via Makefile changes.
> Extend providers interface to support multiple cluster GVKs

- internal/controller/clusterdeployment_controller.go
- providers/aws.yml
- providers/azure.yml
> Fix AKS and EKS cleanup

- config/dev/eks-clusterdeployment.yaml
- templates/cluster/aws-eks/Chart.yaml
- templates/cluster/aws-eks/templates/machinedeployment.yaml
- templates/provider/kcm-templates/files/templates/aws-eks-0-0-6.yaml
- test/e2e/clusterdeployment/resources/aws-eks.yaml.tpl
Closes: https://github.com/k0rdent/kcm/issues/907
> Add `skip-preflight-checks` annotation to EKS machine deployment

- templates/provider/k0smotron/templates/providers.yaml
> Bump k0smotron to v1.4.1

- templates/cluster/aws-hosted-cp/templates/awsmachinetemplate.yaml
- templates/cluster/aws-hosted-cp/values.yaml
- templates/cluster/aws-standalone-cp/templates/awsmachinetemplate-controlplane.yaml
- templates/cluster/aws-standalone-cp/templates/awsmachinetemplate-worker.yaml
- templates/cluster/aws-standalone-cp/values.yaml
> Set uncompressedUserData to false by default in aws clustertemplates

- templates/cluster/aws-hosted-cp/Chart.yaml
- templates/cluster/aws-hosted-cp/values.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/values.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/values.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/values.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/values.yaml
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/values.yaml
> Bump k0s version to v1.31.5+k0s.0

- internal/helm/release.go
> Fix constant helmrelease updates

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/projectsveltos.yaml
- templates/provider/kcm/projectsveltos-crds/accessrequest-crd.yaml
- templates/provider/kcm/projectsveltos-crds/classifier-crd.yaml
- templates/provider/kcm/projectsveltos-crds/classifierreport-crd.yaml
- templates/provider/kcm/projectsveltos-crds/clusterconfiguration-crd.yaml
- templates/provider/kcm/projectsveltos-crds/clusterhealthcheck-crd.yaml
- templates/provider/kcm/projectsveltos-crds/clusterprofile-crd.yaml
- templates/provider/kcm/projectsveltos-crds/clusterreport-crd.yaml
- templates/provider/kcm/projectsveltos-crds/clusterset-crd.yaml
- templates/provider/kcm/projectsveltos-crds/clustersummary-crd.yaml
- templates/provider/kcm/projectsveltos-crds/debuggingconfiguration-crd.yaml
- templates/provider/kcm/projectsveltos-crds/eventreport-crd.yaml
- templates/provider/kcm/projectsveltos-crds/eventsource-crd.yaml
- templates/provider/kcm/projectsveltos-crds/eventtrigger-crd.yaml
- templates/provider/kcm/projectsveltos-crds/healthcheck-crd.yaml
- templates/provider/kcm/projectsveltos-crds/healthcheckreport-crd.yaml
- templates/provider/kcm/projectsveltos-crds/profile-crd.yaml
- templates/provider/kcm/projectsveltos-crds/reloader-crd.yaml
- templates/provider/kcm/projectsveltos-crds/reloaderreport-crd.yaml
- templates/provider/kcm/projectsveltos-crds/rolerequest-crd.yaml
- templates/provider/kcm/projectsveltos-crds/set-crd.yaml
- templates/provider/kcm/projectsveltos-crds/sveltoscluster-crd.yaml
- templates/provider/kcm/projectsveltos-crds/techsupport-crd.yaml
- templates/provider/projectsveltos/Chart.lock
- templates/provider/projectsveltos/Chart.yaml
> update projectsveltos to v0.46.0

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> Update capi-operator to v0.16.0

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> Update cert-manager to v1.17.0

- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/helm/repo.go
- internal/sveltos/profile.go
- internal/webhook/clusterdeployment_webhook.go
> Remove sprintf from log msg

- templates/provider/kcm/templates/deployment.yaml
- templates/provider/kcm/values.schema.json
- templates/provider/kcm/values.yaml
* add all zap flags
* turn off dev logger by default
* regenerate kcm chart schema
Closes #757
> Allow customizing ctrl logger

- api/v1alpha1/multiclusterservice_types.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/multiclusterservice_controller.go
- internal/sveltos/profile.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_multiclusterservices.yaml
> expose ContinueOnError flag for services spec

- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/cluster-api-provider-openstack/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
> Bump openstack-provider to v0.12.0

- test/e2e/clusterdeployment/clusterdeployment.go
- test/e2e/clusterdeployment/providervalidator.go
- test/e2e/clusterdeployment/resources/azure-aks.yaml.tpl
- test/e2e/clusterdeployment/validate_deleted.go
- test/e2e/clusterdeployment/validate_deployed.go
- test/e2e/kubeclient/kubeclient.go
- test/e2e/provider_azure_test.go
- test/e2e/templates/templates.go
> Add Azure AKS e2e testing support

- .gitignore
- Makefile
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_accessmanagements.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clustertemplatechains.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clustertemplates.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_credentials.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_managementbackups.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_managements.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_multiclusterservices.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_providertemplates.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_releases.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_servicetemplatechains.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_servicetemplates.yaml
* rearrange targets
* go-tool-install where applicable
* bump versions
* fix awscli installation for a user without sudo on darwin
* fix small errors fix inexisting binaries
* regenerate crds
Initiated for the #431 but then realized the implementation will no meet expectations but I've decided not to dump the changes
> Makefile chores

- templates/cluster/openstack-standalone-cp/templates/_helpers.tpl
> Enable Openstack MachineTemplate rotation

- Makefile
- config/dev/docker-clusterdeployment.yaml
- config/dev/docker-credentials.yaml
- providers/docker.yml
- templates/cluster/docker-hosted-cp/.helmignore
- templates/cluster/docker-hosted-cp/Chart.yaml
- templates/cluster/docker-hosted-cp/templates/_helpers.tpl
- templates/cluster/docker-hosted-cp/templates/cluster.yaml
- templates/cluster/docker-hosted-cp/templates/dockercluster.yaml
- templates/cluster/docker-hosted-cp/templates/dockermachinetemplate.yaml
- templates/cluster/docker-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/docker-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/docker-hosted-cp/templates/machinedeployment.yaml
- templates/cluster/docker-hosted-cp/values.schema.json
- templates/cluster/docker-hosted-cp/values.yaml
- templates/provider/cluster-api-provider-docker/.helmignore
- templates/provider/cluster-api-provider-docker/Chart.yaml
- templates/provider/cluster-api-provider-docker/templates/provider.yaml
- templates/provider/cluster-api-provider-docker/templates/secret.yaml
- templates/provider/cluster-api-provider-docker/values.schema.json
- templates/provider/cluster-api-provider-docker/values.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-docker.yaml
- templates/provider/kcm-templates/files/templates/docker-hosted-cp-0-1-0.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
> Add Docker provider and cluster template

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-0-1-5.yaml
Catching up on MachineTemplate rotation commit
> Generate Openstack cluster template chart v0.1.5

- config/dev/eks-clusterdeployment.yaml
- templates/cluster/aws-eks/Chart.yaml
- templates/cluster/aws-eks/templates/awsmanagedcontrolplane.yaml
- templates/cluster/aws-eks/values.schema.json
- templates/cluster/aws-eks/values.yaml
- templates/provider/kcm-templates/files/templates/aws-eks-0-1-1.yaml
- test/e2e/clusterdeployment/resources/aws-eks.yaml.tpl
- test/e2e/templates/templates.go
Includes:
1. Expose more settings in the values file for EKS ClusterTemplate
2. Regenerate schema for the EKS cluster template
3. Fix the namespace of AWSManagedControlPlane in the EKS cluster template (remove hardcoded `kcm-system`)
4. Pass `eksClusterName` to the testing EKS cluster for proper cleanup
Closes #962
> Multiple enhancements to the EKS cluster template

- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- internal/helm/release.go
* add retries for the capi release installation
* add extra conditions to ensure component is actually ready for further proceeding
Closes #1094
> Retriable CAPI release

- .github/workflows/build_test.yml
- Makefile
- test/e2e/e2e_suite_test.go
> [e2e] Use local registry for standalone-only deployments

- Makefile
> makefile: check unzip

- internal/helm/actor.go
> Perform server-side dry-run helm install action

- internal/helm/actor.go
> Revert "Perform server-side dry-run helm install action"

- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
> Improve CAPI components status in Management

- .github/workflows/build_test.yml
> Trigger build jobs on a pull request to *-release branch (#1263)

- README.md
> Update the list of CAPI providers in README.md

- Makefile
Cherry-pick https://github.com/k0rdent/kcm/pull/1275
> Fix linux awscli installation

- internal/controller/management_controller.go
> Do not drop unused kcm templates HelmReleases

- config/dev/gke-clusterdeployment.yaml
- internal/controller/clusterdeployment_controller.go
- internal/controller/management_controller.go
- templates/cluster/gcp-gke/values.schema.json
- templates/cluster/gcp-gke/values.yaml
- templates/cluster/gcp-hosted-cp/values.schema.json
- templates/cluster/gcp-hosted-cp/values.yaml
- templates/cluster/gcp-standalone-cp/values.schema.json
- templates/cluster/gcp-standalone-cp/values.yaml
Contains:
* fix objects description for GCP templates
* several minor fixes in config/dev examples
* fixes management components readiness check (collect false condition even if the message is unset)
* do not release ClusterDeployment until Cluster is removed
> Several minor fixes

- internal/controller/multiclusterservice_controller.go
- internal/sveltos/status.go
- internal/sveltos/status_test.go
> Fix incorrect svc readiness calculation

- api/v1alpha1/clusterdeployment_types.go
- api/v1alpha1/credential_types.go
- api/v1alpha1/multiclusterservice_types.go
- internal/controller/accessmanagement_controller.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/metrics/metrics.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_credentials.yaml
* rearrange am reconciler code
* simplify am reconciler code
* unrelated: field alignment and descriptions in other API types
Closes #1234
> AccessManagement ctrl rearrangement

- internal/sveltos/profile.go
- internal/sveltos/profile_test.go
Resolves https://github.com/k0rdent/2a-internal/issues/75
> fix: Ensure nil registry credentials config when no values are set

- templates/provider/cluster-api-provider-k0sproject-k0smotron/Chart.yaml
- templates/provider/cluster-api-provider-k0sproject-k0smotron/templates/providers.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-k0sproject-k0smotron.yaml
This PR updates the k0smotron version to v1.5.1
Fixes #1377
> chore(bump): k0smotron v1.5.1

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/projectsveltos.yaml
- templates/provider/projectsveltos/Chart.lock
- templates/provider/projectsveltos/Chart.yaml
Bump Sveltos to [0.52.2](https://github.com/orgs/projectsveltos/discussions/1154).
Resolves #1426 
K0rdent successfully installed with `make dev-apply` with all components running:
```sh
➜  ~ kubectl get pod -A
NAMESPACE            NAME                                                           READY   STATUS    RESTARTS   AGE
kcm-system           azureserviceoperator-controller-manager-7cb9b87c94-twqc6       1/1     Running   0          4m30s
kcm-system           capa-controller-manager-78bdcdc678-w2kfk                       1/1     Running   0          4m23s
kcm-system           capd-controller-manager-7586b6577c-ph82l                       1/1     Running   0          5m14s
kcm-system           capg-controller-manager-774958b9b9-hp2zz                       1/1     Running   0 …
```
> Bump sveltos to 0.52.2

- .github/workflows/ai-codereview.yml
Fix pattern for finding comment to avoid creating new one
> Change AI code review workflow

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update certmanager version to v1.17.2

- templates/provider/cluster-api-provider-k0sproject-k0smotron/Chart.yaml
- templates/provider/cluster-api-provider-k0sproject-k0smotron/templates/providers.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-k0sproject-k0smotron.yaml
> chore(bump): k0smotron v1.5.2

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/cluster-api-provider-azure/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-azure.yaml
> chore(bump): update azure-provider version to v1.19.3

- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/cluster-api-provider-openstack/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
> chore(bump): update openstack-provider version to v0.12.3

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/cluster-api-provider-azure/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-azure.yaml
> chore(bump): update azure-provider to v1.19.4

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update capi-operator to v0.19.0

- templates/provider/cluster-api-provider-vsphere/Chart.yaml
- templates/provider/cluster-api-provider-vsphere/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-vsphere.yaml
> chore(bump): update vsphere provider version to v1.13.0

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update velero chart to v9.1.2

- templates/provider/cluster-api/Chart.yaml
- templates/provider/cluster-api/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api.yaml
> chore(bump): update capi version to v1.10.1

- templates/provider/kcm/values.yaml
> chore: adjust CAPO resources

- Makefile
> Revert "fix: Rework the helm-push Makefile target"

- api/v1beta1/clusteripam_types.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusteripams.yaml
Simple change to update the clusterIPAMClaimRefs json tag to clusterIPAMClaimRef in ClusterIPAMSpec.
> chore: update clusterIPAMClaimRefs to clusterIPAMClaimRef

- README.md
Updated list of default providers along with the defaults of a ClusterDeployment and its `.status` changing resource API version to `v1beta1`
> docs: amend readme with updates

- cmd/main.go
- internal/helm/repo.go
- templates/provider/kcm/templates/deployment.yaml
- templates/provider/kcm/values.schema.json
- templates/provider/kcm/values.yaml
> enh: Pass certificate secret to the default helm repository

- README.md
- config/dev/aws-clusterdeployment.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/aws-standalone-cp-1-0-4.yaml
> fix: Correct the k0s version of aws-standalone-cp

- templates/provider/cluster-api-provider-aws/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-aws.yaml
> chore(bump): update aws provider version to v2.8.3

- internal/controller/management_controller.go
> fix: don't expect operator provider in ProviderTemplates

- templates/provider/cluster-api/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api.yaml
> chore(bump): update capi version to v1.10.3

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update cert-manager to v1.18.1

- Makefile
- api/v1beta1/clusteripamclaim_types.go
- config/dev/vsphere-clusterdeployment.yaml
- internal/controller/clusterdeployment_controller.go
- internal/controller/ipam/adapter/ipam_incluster_adapter.go
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/templates/vspheremachinetemplate-controlplane.yaml
- templates/cluster/vsphere-standalone-cp/templates/vspheremachinetemplate-worker.yaml
- templates/cluster/vsphere-standalone-cp/values.schema.json
- templates/cluster/vsphere-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm-templates/files/templates/vsphere-standalone-cp-1-0-4.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusteripamclaims.yaml
Fix to IPAM claim processing when the claim is inline within the ClusterDeployment CRD. Fixes #1592
> fix: IPAM claim inline processing

- internal/controller/clusterdeployment_controller.go
Originally in the ClusterDeployment reconcile, we were checking to see if there are sill any services running on the target CAPI cluster before releasing it by:
1. Listing all Sveltos ClusterSummaries that match the target cluster via labels.
2. Checking if helm release is in "Managing" state for each ClusterSummary.
1. Create a ClusterDeployment
2. Deploying a service on it via a MultiClusterService
3. Deleting the ClusterDeployment
The CD does not get deleted because the cluster still had a service running on it (deployed via the MCS). Which is due to the recent check we merged in through which we check if all services were removed from the cluster before deleting it:
```
2025-06-16T22:35:45Z	INFO	services need to be removed prior to deletion of ClusterDeployment, retrying
```
Since a …
> fix: check if services from self are running before deleting ClusterDeployment

- templates/provider/cluster-api-provider-k0sproject-k0smotron/Chart.yaml
- templates/provider/cluster-api-provider-k0sproject-k0smotron/templates/providers.yaml
- templates/provider/cluster-api-provider-k0sproject-k0smotron/values.schema.json
- templates/provider/cluster-api-provider-k0sproject-k0smotron/values.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-k0sproject-k0smotron.yaml
This PR adds support to override manager parameters for k0smotron.
**Which issue(s) this PR fixes** _(optional, `Fixes #123`)_: Fixes #1737
> feat: Support to override manager parameters for k0smotron

- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
> chore(bump): update openstack provider to v0.12.4

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update capi-operator to v0.21.0

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-azure.yaml
> chore(bump): update azure provider to v1.20.1

- templates/provider/cluster-api-provider-vsphere/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-vsphere.yaml
> chore(bump): update vsphere provider to v1.13.1

- templates/provider/cluster-api-provider-aws/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-aws.yaml
> chore(bump): update aws provider to v2.8.4

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update capi-operator to v0.22.0

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
> fix: add configmaps ro rbac to kcm role

- .github/workflows/build_test.yml
> ci: add missing quote to support bundles path

- test/e2e/clusterdeployment/azure/azure.go
**What this PR does / why we need it**: With the previous image, we faced https://github.com/k0rdent/kcm/issues/1817.
Related task: #1817
> test: Update Azure arm64 image in e2e

- internal/sveltos/profile.go
Remove excessive fetching of ServiceTemplate objects during getting a referenced one from a Service
> fix: redundant servicetemplates fetching

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
> chore(bump): update capi-operator to v0.23.0

- templates/provider/cluster-api/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api.yaml
> chore(bump): update capi to v1.10.5

- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-azure.yaml
> chore(bump): update capi-azure version to v1.21.0

- Makefile
This PR introduces a `dev-upgrade` Makefile target that performs an upgrade of the dev environment (originally set up with `make dev-apply`).
Example workflow: upgrading from `v1.3.1` to the current main:
```
git checkout v1.3.1
make dev-apply
kubectl wait management kcm --for=condition=Ready=True --timeout 10m
git checkout main
make dev-upgrade
```
Fixes #1700
> chore: add make dev-upgrade target to upgrade dev kcm

- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
> chore(bump): update openstack provider to v0.13.0

- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
> revert: update openstack provider to v0.13.0

- templates/provider/kcm-regional/Chart.lock
- templates/provider/kcm-regional/Chart.yaml
- templates/provider/kcm-regional/values.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm-regional.yaml
- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
Bumps kcm's velero chart to v11.0.0.
Closes #2053
> chore(bumps): velero chart
