- config/default/hmc_values.yaml
- templates/hmc/values.yaml
HMC-109
Flux chart installs network policies by default. It breaks networking connectivity, so they should be disabled.
> Disable Flux network policies creation

- README.md
- templates/aws-standalone-cp/templates/awsmachinetemplate-controlplane.yaml
- templates/aws-standalone-cp/templates/awsmachinetemplate-worker.yaml
- templates/aws-standalone-cp/values.yaml
HMC-110
This configuration  option will only be useful if we’re using existing VPC (like in the aws-hosted-cp), but it’s not supported in the `aws-standalone-cp`, so it should be removed.
> Remove additionalSecurityGroupIDs parameter for aws-standalone

- templates/aws-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/aws-standalone-cp/templates/k0scontrolplane.yaml
HMC-116
Currently we’re only installing CCM with our deployments. No CSI is present, so in order for user to use PVCs it should install CSI separately, which is inconvenient.
> Install EBS CSI driver by default

- Makefile
'make clusterawsadm' uses the ARCH var to craft a URL for downloading the clusterawsadm binary but 'uname -m' outputs the arch as 'x86_64' while the binary versions for download use 'amd64', this modifies the arch outputted by 'uname -m' to use 'amd64' so that the curl does not fail with 'Not Found'.
Before `make clusterawsadm`  curled a URL that does not exist and outputted a bin file with `Not Found`:
```
$ make clusterawsadm
$ curl -sL https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.5.2/clusterawsadm_v2.5.2_linux_x86_64 -o /home/squizzi/go/src/github.com/Mirantis/hmc/bin/clusterawsadm
chmod +x /home/squizzi/go/src/github.com/Mirantis/hmc/bin/clusterawsadm
$ curl -sL https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.5.2/clus …
```
> Fix Makefile's use of ARCH to rename x86_64 to amd64, fix kind-deploy/undeploy target

- templates/aws-standalone-cp/templates/awscluster.yaml
Fixes #159 
Opened only port 9443. 
We're also missing 112 (keepalived) and 8132 (konnectivity) from [the table](https://docs.k0sproject.io/v1.30.3+k0s.0/networking/#required-ports-and-protocols), but since we're not using either of them they can be ignored
> Open port 9443 (k0s join API) for all controllers

- docs/aws/cluster-parameters.md
- templates/aws-hosted-cp/templates/awscluster.yaml
- templates/aws-hosted-cp/templates/awsmachinetemplate.yaml
- templates/aws-hosted-cp/values.schema.json
- templates/aws-hosted-cp/values.yaml
- templates/aws-standalone-cp/templates/awscluster.yaml
- templates/aws-standalone-cp/templates/awsmachinetemplate-controlplane.yaml
- templates/aws-standalone-cp/templates/awsmachinetemplate-worker.yaml
- templates/aws-standalone-cp/values.schema.json
- templates/aws-standalone-cp/values.yaml
> Add bastion configuration for AWS templates

- templates/aws-hosted-cp/Chart.yaml
- templates/aws-hosted-cp/templates/_helpers.tpl
- templates/aws-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/aws-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/aws-standalone-cp/Chart.yaml
- templates/aws-standalone-cp/templates/_helpers.tpl
- templates/aws-standalone-cp/templates/k0scontrolplane.yaml
- templates/aws-standalone-cp/templates/k0sworkerconfigtemplate.yaml
- templates/hmc-templates/files/templates/aws-hosted-cp.yaml
- templates/hmc-templates/files/templates/aws-standalone-cp.yaml
- templates/hmc-templates/files/templates/k0smotron.yaml
- templates/k0smotron/Chart.yaml
- templates/k0smotron/values.yaml
> K0smotron bump

- Makefile
- README.md
- cmd/main.go
- config/dev/hmc_values.yaml
- internal/controller/release_controller.go
- templates/hmc/templates/deployment.yaml
- templates/hmc/templates/serviceaccount.yaml
- templates/hmc/values.schema.json
- templates/hmc/values.yaml
> Automatically create Management object only once

- api/v1alpha1/management_types.go
- internal/controller/management_controller.go
- internal/webhook/management_webhook.go
Still keeping the same code in the management controller to handle the case when the admission has not started yet.
Closes #140
> Apply Management defaults by the admission controller

- internal/utils/util.go
- internal/webhook/deployment_webhook.go
> Validate Deployment objects

- templates/hmc/values.yaml
Also remove a deprecated value used to install CRDs
Closes #192
> Don't keep created cert-manager CRDs of on HMC deletion

- api/v1alpha1/deployment_types.go
- templates/hmc/templates/crds/hmc.mirantis.com_deployments.yaml
We should ensure the `spec.template` field is set and is not empty. `kubebuilder:validation:Required` marker is not enough since an empty template bypasses the validation: https://github.com/kubernetes-sigs/kubebuilder/issues/3675
> Specify minLength validation for deployment's template reference

- cmd/main.go
- internal/telemetry/event.go
- internal/telemetry/tracker.go
- templates/hmc/templates/deployment.yaml
- templates/hmc/values.schema.json
- templates/hmc/values.yaml
Added a new poller to track the deployments status in the heartbeat event according to the tracking plan every 10 minutes.
To analyse and decrease memory and CPU usage the following approaches were tested on 1000 test deployments:
Testing discovered that the first approach performed best on the management cluster. It was tested using the metrics server (`kubectl top pod`):
1. List all deployments using the default (cached) manager client
```
NAMESPACE            NAME                                            CPU           Memory
hmc-system           hmc-controller-manager-58bbbc8d7c-wkpfs         6m            67Mi
kube-system          kube-apiserver-hmc-dev-control-plane            82m           562Mi
```
2. List all deployments using uncached manager client
```
NAMESPACE …
```
> Track deployment status

- api/v1alpha1/deployment_types.go
- cmd/main.go
- internal/controller/deployment_controller.go
- internal/controller/deployment_controller_test.go
- templates/hmc/templates/rbac/roles.yaml
Resolves #219. This PR adds a new function that fetches the CAPI status / conditions of the cluster and places them in the deployment status/conditions. To ensure the conditions are updated the controller now requeues until the CAPI cluster conditions are all true.
> Add CAPI status/conditions to deployment status

- docs/azure/cluster-parameters.md
- templates/azure-standalone-cp/.helmignore
- templates/azure-standalone-cp/Chart.yaml
- templates/azure-standalone-cp/templates/_helpers.tpl
- templates/azure-standalone-cp/templates/azurecluster.yaml
- templates/azure-standalone-cp/templates/azuremachinetemplate-controlplane.yaml
- templates/azure-standalone-cp/templates/azuremachinetemplate-worker.yaml
- templates/azure-standalone-cp/templates/cluster.yaml
- templates/azure-standalone-cp/templates/k0scontrolplane.yaml
- templates/azure-standalone-cp/templates/k0sworkerconfigtemplate.yaml
- templates/azure-standalone-cp/templates/machinedeployment.yaml
- templates/azure-standalone-cp/values.schema.json
- templates/azure-standalone-cp/values.yaml
- templates/hmc-templates/files/templates/azure-standalone-cp.yaml
> Add Azure standalone CP template

- go.mod
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/utils/kube.go
- internal/webhook/deployment_webhook.go
* properly leverage multierr feature via `errors.Join`
* side: removed undesired package from the direct dependencies
Fixes #258
> Fix erroneous `errors.Join` usage

- PROJECT
- config/dev/aws-managedcluster.yaml
- config/dev/azure-managedcluster.yaml
In https://github.com/Mirantis/hmc/pull/265 we changed the code from `Deployment` to `ManagedCluster`, this also updates the examples
> update dev examples from `Deployment` to `ManagedCluster`

- cmd/main.go
- config/dev/hmc_values.yaml
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/utils/helm.go
- internal/utils/helm_test.go
- templates/hmc/templates/deployment.yaml
- templates/hmc/values.yaml
While working on figuring out what registry to use for CI in #220  I thought why not use Mirantis Secure Registry (MSR)?welp.. that was a journey.
Currently we hardcode the `HelmRepostory` type to `oci` when reconciling the default `hmc-templates` repository.  The problem with this is, for whatever reason, MSR does not like OCI (even though, I'm pretty sure it implements the spec) and it results in `insufficient_scope` errors when we try to pull the charts.  After some digging through `helm-controller` CRDs and docs I discovered this setting: https://fluxcd.io/flux/components/source/helmrepositories/#type and changed our `HelmRepository` we reconcile to use `'default'` which fixed the issue and pulled the chart with no problems.
---
This patch renames the existing 'defaultOCIRegistry' …
> Add defaultRegistryURL and defaultRepoType for non-OCI HelmRepository support

- config/dev/aws-managedcluster.yaml
- templates/aws-standalone-cp/values.yaml
Disabling installBeachHeadServices by default on `aws-standalone-cp` template to address https://github.com/Mirantis/hmc/issues/286.
> Disable installBeachHeadServices by default on `aws-standalone-cp` template

- api/v1alpha1/common.go
- api/v1alpha1/management_types.go
- internal/controller/managedcluster_controller.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/helm/release.go
- templates/provider/hmc-templates/files/templates/projectsveltos.yaml
- templates/provider/projectsveltos/Chart.lock
- templates/provider/projectsveltos/Chart.yaml
This fixes [#269](https://github.com/Mirantis/hmc/issues/269).
1. Sveltos is installed (via it's [helm chart](https://github.com/projectsveltos/helm-charts)) as a `provider` type template.
2. The reason it is installed as a separate template rather than as a subchart within the HMC template is because Sveltos needs to be installed in the `projectsveltos` namespace for it to function.
3. We already tried installing Sveltos in `hmc-system` namespace but it didn't work properly, the details of which can be [seen here](https://github.com/Mirantis/2a-internal/issues/5#issuecomment-2334128875).
Installed with AWS provider and waited for everything to be in running state.
- Verified that Sveltos template has been created:
```sh
➜  ~ kubectl get template -A
NAMESPACE    NAME …
```
> Install Sveltos as a Provider Template

- .gitignore
- api/v1alpha1/managedcluster_types.go
- internal/controller/managedcluster_controller.go
- templates/cluster/aws-hosted-cp/templates/awscluster.yaml
- templates/cluster/azure-hosted-cp/templates/azurecluster.yaml
- templates/provider/hmc/templates/rbac/roles.yaml
Fixing https://github.com/Mirantis/hmc/issues/217
This fix is intended to resolve an issue when deletion of HelmRelease resulted to non-deleted (orphaned) objects.
The root cause of the issue was with the removal AWSCluster while Machine objects have not been deleted.
> Improved HelmRelease deletion

- Makefile
- config/dev/vsphere-credentials.yaml
- config/dev/vsphere-managedcluster.yaml
- docs/dev.md
- test/e2e/e2e_test.go
- test/kubeclient/kubeclient.go
- test/managedcluster/managedcluster.go
- test/managedcluster/resources/vsphere-hosted-cp.yaml.tpl
- test/managedcluster/resources/vsphere-standalone-cp.yaml.tpl
- test/managedcluster/validate_deleted.go
- test/managedcluster/validate_deployed.go
- test/utils/vsphere/vsphere.go
Partially resolves #254 , since it doesn't include hosted CP test.
Notes:
- To run the test `TEST_VSPHERE` must be set to any value, otherwise it will be skipped, since it will fail without special runner.
- CCM validation disabled, LodaBalancer Service is not created by CCM (and kube-vip requires an annotation) thus this test will fail.
- cluster identity is created using unstructured nonsense, because I don't see how to force client-go to use normal types without mangling with restclient (which doesn't look much better than the unstructured nonsense).
> Add vSphere e2e standalone test

- internal/webhook/management_webhook.go
- internal/webhook/management_webhook_test.go
Added code for rejecting of reenabling the createManagement parameter in Management HMC spec.
Implements https://github.com/Mirantis/hmc/issues/245
> Added reenabling of the createManagement parameter check

- config/dev/aws-credentials.yaml
Simple fix to restore the AWS_SESSION_TOKEN functionality for aws credentials.
> Restore missing session token variable for aws credentials

- Makefile
- scripts/awscli-darwin-install.xml.tpl
Unfortunately using `installer` on MacOS requires `sudo` even though it's installing into `$LOCALBIN`, but this works for now.  There doesn't seem to be any other way to get the binary into `$LOCALBIN` other then getting other dependencies like `pip` or `brew` involved. An annoying one for sure.
Closes: #365
> Fix `make awscli` on darwin

- Makefile
This `set -x` snuck in with the latest changes in #376, it was on my local but I forgot to push it apparently.
> Remove debugging from `make awscli` target

- api/v1alpha1/management_types.go
- api/v1alpha1/templatemanagement_types.go
- cmd/main.go
- internal/controller/release_controller.go
- internal/controller/templatemanagement_controller_test.go
- internal/webhook/templatemanagement_webhook.go
- internal/webhook/templatemanagement_webhook_test.go
- templates/provider/hmc/templates/deployment.yaml
- templates/provider/hmc/templates/rbac/controller/roles.yaml
- templates/provider/hmc/values.schema.json
- templates/provider/hmc/values.yaml
- test/objects/management/management.go
1. Support automatically creating the `TemplateManagement` with no access rules (enabled by default).
2. Forbid the creation of more than one `TemplateManagement` object.
3. Forbid the removal of the `TemplateManagement` object if the Management object exists and was not triggered for the deletion.
Closes #373
> Handle TemplateManagement creation and removal

- .github/workflows/test.yml
- Makefile
- test/e2e/e2e_test.go
- test/managedcluster/aws/aws.go
- test/managedcluster/azure/azure.go
- test/managedcluster/managedcluster.go
- test/managedcluster/providervalidator.go
- test/managedcluster/resources/aws-hosted-cp.yaml.tpl
- test/managedcluster/resources/aws-standalone-cp.yaml.tpl
- test/managedcluster/resources/azure-hosted-cp.yaml.tpl
- test/managedcluster/resources/azure-standalone-cp.yaml.tpl
- test/managedcluster/resources/vsphere-hosted-cp.yaml.tpl
- test/managedcluster/resources/vsphere-standalone-cp.yaml.tpl
- test/managedcluster/validate_deployed.go
Implement Azure template e2e tests. Closes https://github.com/Mirantis/hmc/issues/210.
> Implemented Azure e2e tests

- config/dev/aws-credentials.yaml
- config/dev/aws-managedcluster.yaml
- config/dev/azure-credentials.yaml
- config/dev/azure-managedcluster.yaml
- config/dev/vsphere-credentials.yaml
- config/dev/vsphere-managedcluster.yaml
Adding `Credential` to the YAML files for AWS under `dev/config`.  This is needed after https://github.com/Mirantis/hmc/pull/342 was merged. Without this the HMC Operator keeps on failing with:
```sh
ster", "ManagedCluster": {"name":"wali-aws-dev","namespace":"hmc-system"}, "namespace": "hmc-system", "name": "wali-aws-dev", "reconcileID": "de457532-16dd-466a-afe0-e8c5d410ecf4", "error": "Credential.hmc.mirantis.com \"\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller. …
```
> Add `Credential` to dev config for AWS

- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/templates/k0scontrolplane.yaml
- templates/provider/hmc-templates/files/templates/vsphere-hosted-cp.yaml
- templates/provider/hmc-templates/files/templates/vsphere-standalone-cp.yaml
Pulls in fix for default repo from https://github.com/Mirantis/helm-charts/pull/1
> Bump vsphere-csi-driver to 0.0.2

- api/v1alpha1/common.go
- internal/webhook/template_webhook.go
- internal/webhook/template_webhook_test.go
- internal/webhook/templatechain_webhook_test.go
- test/objects/managedcluster/managedcluster.go
Closes https://github.com/Mirantis/hmc/issues/316.
Originally I wrote the create validation for [Cluster/Service]TemplateChain to check if the templates being referenced in `.Spec.SupportedTemplates` actually existed in the same namespace. However, looking at how https://github.com/Mirantis/hmc/pull/407 has been implemented I dumped that so there is no validation check happening for create now.
> Add validation for ServiceTemplateChain

- api/v1alpha1/common.go
- internal/webhook/template_webhook.go
- templates/provider/hmc/templates/webhooks.yaml
Missed adding this to https://github.com/Mirantis/hmc/pull/416.
Deletes on `ServiceTemplate` now blocked if it is referenced in a `ManagedCluster` object:
```sh
➜  ~ khmc delete servicetemplate ingress-nginx 
Warning: The ServiceTemplate object can't be removed if ManagedCluster objects referencing it still exist
Error from server (Forbidden): admission webhook "validation.servicetemplate.hmc.mirantis.com" denied the request: template deletion is forbidden
```
> Add Webhooks for ServiceTemplate to ValidatingWebhookConfiguration

- internal/controller/management_controller.go
Small fix without which Sveltos will not install because the template names now have versions appended to them. See https://github.com/Mirantis/hmc/pull/436.
HMC can install Sveltos now:
```sh
➜  ~ kubectl -n hmc-system get helmreleases.helm.toolkit.fluxcd.io projectsveltos 
NAME             AGE     READY   STATUS
projectsveltos   3m34s   True    Helm install succeeded for release projectsveltos/projectsveltos.v1 with chart projectsveltos@0.38.2
➜  ~ 
➜  ~ kubectl -n projectsveltos get deployment
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
access-manager          1/1     1            1           2m54s
addon-controller        1/1     1            1           2m54s
classifier-manager      1/1     1            1           2m54s
conversion-webhook      1/1     1            1 …
```
> Fix bug introduced in Sveltos install

- config/dev/hmc_values.yaml
- internal/controller/release_controller.go
- internal/utils/release.go
Small change to use the createRelease flag and not create the release if the flag is false.
> Honor the createRelease flag when reconciling

- api/v1alpha1/release_types.go
- internal/controller/template_controller.go
- internal/controller/template_controller_test.go
- internal/webhook/managedcluster_webhook.go
- internal/webhook/managedcluster_webhook_test.go
* move clustertemplates compatibility verification from the validationwebhook to the tpl ctrl
* correspinding integration tests
Related Issue: https://github.com/Mirantis/hmc/issues/400
> Compatibility attributes amends

- .github/workflows/build_test.yml
The leading `v` was removed from `VERSION` in #505, but the test outputs get generated outside of the `Makefile`, this fixes the version used within the test workflow as well.  Unfortunately, with the nature of `pull_request_target` the CI won't pass until merged because this is a workflow file change (we really need to change this behavior when things cool down around here)
> Strip leading v from VERSION in 'Get outputs' job

- internal/controller/managedcluster_controller.go
Fixing https://github.com/Mirantis/hmc/issues/491 (to avoid error messages where EKS cluster was mistaken with AWS one).
Simplified the code.
> Fix an issue with EKS cluster removal

- templates/provider/cluster-api-provider-aws/Chart.yaml
- templates/provider/cluster-api-provider-azure/Chart.yaml
- templates/provider/cluster-api-provider-vsphere/Chart.yaml
- templates/provider/cluster-api/Chart.yaml
- templates/provider/hmc-templates/Chart.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-aws.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-azure.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-vsphere.yaml
- templates/provider/hmc-templates/files/templates/cluster-api.yaml
- templates/provider/hmc-templates/files/templates/hmc.yaml
- templates/provider/hmc-templates/files/templates/k0smotron.yaml
- templates/provider/hmc/Chart.yaml
- templates/provider/k0smotron/Chart.yaml
> Update template versions for 0.0.3

- internal/controller/managedcluster_controller.go
- internal/controller/managedcluster_controller_test.go
- internal/webhook/managedcluster_webhook.go
- internal/webhook/managedcluster_webhook_test.go
- test/objects/credential/credential.go
- test/objects/managedcluster/managedcluster.go
Resolves #392 
Also added basic unit tests for validations.
> Add credential admission checks for managedcluster

- config/dev/aws-managedcluster.yaml
Followup to https://github.com/Mirantis/hmc/pull/502. We don't need it anymore.
> Remove installBeachHeadServices from sample template

- internal/webhook/managedcluster_webhook.go
- internal/webhook/managedcluster_webhook_test.go
Validate template only in case it was updated in the cluster's spec
Closes #244
> Improve ManagedCluster update validation

- .github/workflows/build_test.yml
With our change to `pull_request_target` for workflow runs, `actions/checkout` needs to be updated to grab the ref from the PR, not from where the job is running.  This is because `pull_request_target` runs on the target branch.
This PR uses the GitHub API to fetch the merge commit sha and use that as the ref for `actions/checkout`
> Get the PR ref from the merge commit within `pull_request_target` workflows

- docs/dev.md
- internal/controller/managedcluster_controller.go
- internal/credspropagation/azure.go
- internal/credspropagation/common.go
- internal/credspropagation/vsphere.go
> Credentials propagation improvements + dev docs

- cmd/main.go
- internal/controller/managedcluster_controller.go
- internal/controller/management_controller.go
- internal/utils/status/status.go
- templates/provider/hmc/templates/rbac/controller/roles.yaml
- test/e2e/kubeclient/kubeclient.go
- test/e2e/managedcluster/validate_deleted.go
- test/e2e/managedcluster/validate_deployed.go
- test/utils/utils.go
In this PR we now update our component statuses by iterating the provider CRDs affiliated with CAPI operator and returning a status error if any of the `status.conditions` are `False` or if we cannot obtain any information pertaining to status condition.  For example:
In this case `cluster-api-provider-aws` and `-azure` are not yet installed:
```
status:
availableProviders: {}
components:
cluster-api:
success: true
cluster-api-provider-aws:
error: 'failed to find any provider resources affiliated with template: cluster-api-provider-aws'
cluster-api-provider-azure:
error: 'failed to find any provider resources affiliated with template: cluster-api-provider-azure'
hmc:
success: true
k0smotron:
success: true
```
In this case `cluster-api-provider-aws` is reporting some status conditions …
> Get status.conditions from CAPI operator during `updateComponentsStatus`

- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- internal/controller/suite_test.go
- internal/utils/kube.go
* if component is removed from management object the related helmreleases, providertemplates and helmcharts are deleted now
* small code amends
* test coverage for the mgmt-ctrl raised from 4.4% to 45.8%
Closes #553
> Cleanup component dependencies when removed

- .github/workflows/release.yml
This updates our release action with two steps which create the airgap package tarball and then upload it to our binary2a.mirantis.com S3 bucket.
Note that this action will not work until the secrets affiliated with the S3 are populated in the GitHub secrets store.  @DinaBelova or @Kshatrix should work with Roman Vyalov to populate those secrets since today is my last day at Mirantis.
I don't have a way to test this since I don't have access to the s3 bucket, but I figured writing a starting point would be helpful for someone to carry.
> Update release actions with airgap bundle upload

- .github/workflows/build_test.yml
- Makefile
By default, the `golangci/golangci-lint-action` uses the latest linter version (currently v1.62.0). With the linter of v1.62.0 version, the `max-public-structs` linter shows a false-positive result.
Currently, in our Makefile, we have the linter version pinned to `v1.61.0`. This PR ensures consistency by aligning the linter version in the GitHub Actions workflow with the version used in the Makefile (which is used locally).
Closes #624
> Use linter from makefile target in the build workflow

- scripts/bundle-images.sh
This PR fixes the values processing for 2A extensions:
1. Run `helm template` before getting values for extensions:
```
${HELM} template "${template}" --show-only "${k0sconfig}" | $YQ e "${extensions_path}.charts[] | select(.chartname == \"*$chartname*\") | .values" > ${name}-values.yaml
```
instead of
```
grep -vw "{{" $template | $YQ e "${extensions_path}.charts[] | select(.chartname == \"*$chartname*\") | .values" > ${name}-values.yaml
```
3. Rename `templates_dir` -> `TEMPLATES_DIR`
Closes #654
> [airgap] Fix values processing for 2A extensions

- README.md
- config/dev/aws-managedcluster.yaml
`config/dev/aws-managedcluster.yaml` still points to `aws-standalone-cp-0-0-2`, should be `aws-standalone-cp-0-0-3` post merge of #658.
Right now, I'm getting the following error during a local dev.
```
➜  make dev-mcluster-apply
Error from server (NotFound): error when creating "STDIN": admission webhook "validation.m
anagedcluster.hmc.mirantis.com" denied the request: ClusterTemplate.hmc.mirantis.com "aws-
standalone-cp-0-0-2" not found
make: *** [dev-mcluster-apply] Error 1
```
Fix found through collaboration with @bnallapeta 🙌🏼
> Dev deploy fix - update dev/config aws cluster template version to 0-0-3

- Makefile
- go.mod
- go.sum
- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- internal/controller/suite_test.go
Includes:
1.	Check the readiness of the HelmRelease before verifying the CAPI provider objects.
2.	Fix the label selector to correctly find all CAPI provider objects related to the HelmRelease.
3.	Skip checking CAPI provider objects' conditions for HMC and Sveltos Helm releases.
4.	Improve error messages to provide clearer information.
5.	Adapt the testing to reflect the changes.
Closes #581
> Fix providers status reporting in management object

- .github/workflows/release.yml
- scripts/bundle-images.sh
Currently airgap bundle creation fails with:
```
the input device is not a TTY
```
Which prevents to gather list of images and thus providing the bundle with a single image.
The `IMG` variable points to some garbage, fixed as well.
> Fix Airgap bundle creation in CI

- config/dev/aws-managedcluster.yaml
- internal/controller/managedcluster_controller.go
- internal/sveltos/profile.go
1. Pass private repository credentials to Sveltos objects ([#625](https://github.com/Mirantis/hmc/issues/625)).
2. Do not return without reconciling services even if reconciling cluster fails ([#640](https://github.com/Mirantis/hmc/issues/640)).
I created the following `myappz-0-4-0` serviceTemplate which references a chart in `oci://registry-1.docker.io/wali90` private repository:
```yaml
apiVersion: v1
kind: Secret
data:
.dockerconfigjson: # redacted base64 string of {"auths":{"https://registry-1.docker.io/wali90":{"username":"?","password":"?","auth":"<base64 of user:pass>"}}}
metadata:
name: dockerhub-creds-dockerconfig-oci
namespace: hmc-system
type: kubernetes.io/dockerconfigjson
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
labels: …
```
> Pass pvt repo creds to Sveltos & make services reconcile independent

- internal/controller/suite_test.go
We test them separately and it's a bit of an unnecessary burden to have them in the controller tests.
> Disable validating webhooks for controller tests

- .gitignore
- hack/collect-airgap-providers.sh
Related to #709
Quick fix to not block azure provider installation/testing, since proper fix of #709 may take more time.
I removed AWS as well, since it also doesn't make much sense in the airgap environment.
Also I added generated files directories to `gitignore` to avoid dirty state (which could be annoing)
> Don't collect CAPI manifests for public clouds + gitignore fix

- cmd/main.go
- internal/controller/suite_test.go
- internal/controller/template_controller_test.go
- internal/webhook/release_webhook.go
- internal/webhook/template_webhook.go
- internal/webhook/template_webhook_test.go
- templates/provider/hmc/templates/webhooks.yaml
- test/objects/template/template.go
- test/objects/templatechain/templatechain.go
The following template deletion rules are validated:
1. `ClusterTemplate` or `ServiceTemplate` can't be removed if it is in use by `ManagedCluster` or owned by `TemplateChain`
2. `ProviderTemplate` can't be removed if it's a core provider or enabled in Management `spec.providers`
Closes #329
> Improve Templates deletion validation

- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/projectsveltos.yaml
- templates/provider/projectsveltos/Chart.lock
- templates/provider/projectsveltos/Chart.yaml
> Bump sveltos to v0.44.0

- api/v1alpha1/backup_types.go
- api/v1alpha1/management_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- cmd/main.go
- templates/provider/hmc/templates/crds/hmc.mirantis.com_backups.yaml
- templates/provider/hmc/templates/crds/hmc.mirantis.com_managements.yaml
- templates/provider/hmc/templates/rbac/controller/roles.yaml
* added required permission to the mgr role
* disabled ctrl until the actual implementation
* fixes to the API regarding discussion
Closes #759
> Fix backups absent permissions

- README.md
- config/dev/aws-managedcluster.yaml
- config/dev/azure-managedcluster.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/templates/awscluster.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/templates/azurecluster.yaml
- templates/provider/hmc-templates/files/templates/aws-standalone-cp-0-0-4.yaml
- templates/provider/hmc-templates/files/templates/azure-standalone-cp-0-0-4.yaml
- test/e2e/managedcluster/resources/aws-standalone-cp.yaml.tpl
- test/e2e/managedcluster/resources/azure-standalone-cp.yaml.tpl
> Add cleanup finalizer for aws/azure standalone templates

- Makefile
- api/v1alpha1/common.go
- api/v1alpha1/compatibility_contract.go
- api/v1alpha1/compatibility_contract_test.go
- api/v1alpha1/management_types.go
- api/v1alpha1/templates_common.go
- internal/certmanager/verifier.go
- internal/controller/accessmanagement_controller_test.go
- internal/controller/managedcluster_controller.go
- internal/controller/template_controller.go
- internal/credspropagation/common.go
- internal/helm/chart.go
- internal/utils/kube.go
- internal/webhook/management_webhook_test.go
- internal/webhook/templatechain_webhook.go
* fix comment/naming (closes #754)
* comment isNonMajor, provide examples (closes #753)
* simplifie VerifyAPI (closes #758)
* enhance helmSpec String symbol (closes #756)
* simplified makeClientFromSecret (closes #762)
* renamed ArtifactReady and commented out (closes #764)
* added const for SA NS path in CurrentNamespace symbol (closes #772)
* isTemplateChainValid symbol: advice maps with the len (closes #774)
* validateReleaseWithValues symbol: simplify (closes #776)
* fix typo in test node name (closes #783)
* call linter from a single make target (closes #796)
> Fix numerous issues

- internal/credspropagation/azure.go
> Fix azure.json generation: include node-subnet data

- api/v1alpha1/common.go
- api/v1alpha1/management_types.go
- templates/provider/cluster-api-provider-openstack/.helmignore
- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/cluster-api-provider-openstack/templates/provider.yaml
- templates/provider/cluster-api-provider-openstack/templates/secret.yaml
- templates/provider/cluster-api-provider-openstack/values.schema.json
- templates/provider/cluster-api-provider-openstack/values.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api-provider-openstack.yaml
Resolves https://github.com/Mirantis/hmc/issues/594.
OpenStack Provider Integration:
- Introduces OpenStack as a supported cloud provider in HMC.
- Adds configurations and provider templates specific to OpenStack environments.
Local Run:
```
ka get machines
NAME                           CLUSTER         NODENAME                       PROVIDERID                                          PHASE     AGE     VERSION
openstack-dev-cp-0             openstack-dev   openstack-dev-cp-0             openstack:///b52ccc71-566b-4487-a0b8-64b2c08f0e5b   Running   8m29s   v1.30.5+k0s.0
openstack-dev-cp-1             openstack-dev   openstack-dev-cp-1             openstack:///4022efcb-da46-4a99-80f3-2eaf3681238e   Running   8m29s   v1.30.5+k0s.0
openstack-dev-cp-2             openstack-dev …
```
> Add OpenStack provider support with configuration and templates

- Makefile
- api/v1alpha1/clusterdeployment_types.go
- config/dev/aks-clusterdeployment.yaml
- config/dev/aks-credentials.yaml
- internal/controller/clusterdeployment_controller.go
- internal/webhook/clusterdeployment_webhook.go
- templates/cluster/azure-aks/.helmignore
- templates/cluster/azure-aks/Chart.yaml
- templates/cluster/azure-aks/templates/_helpers.tpl
- templates/cluster/azure-aks/templates/azureasomanagedcluster.yaml
- templates/cluster/azure-aks/templates/azureasomanagedcontrolplane.yaml
- templates/cluster/azure-aks/templates/azureasomanagedmachinepool-controlplane.yaml
- templates/cluster/azure-aks/templates/azureasomanagedmachinepool-worker.yaml
- templates/cluster/azure-aks/templates/cluster.yaml
- templates/cluster/azure-aks/templates/machinepool-controlplane.yaml
- templates/cluster/azure-aks/templates/machinepool-worker.yaml
- templates/cluster/azure-aks/values.schema.json
- templates/cluster/azure-aks/values.yaml
- templates/provider/hmc-templates/files/templates/azure-aks-0-0-1.yaml
- templates/provider/hmc/templates/crds/hmc.mirantis.com_clusterdeployments.yaml
This PR introduces the following changes:
1. A new template for `azure-aks` clusters has been added.
2. The ClusterDeployment spec now supports the option to skip propagating credentials by setting `propagateCredentials: false`. This is particularly needed for AKS clusters, as they do not require credential propagation.
3. Added YAMLs with AKS credentials and managed cluster.
There are two API options for creating AKS clusters: `ManagedCluster` and `ASOManagedCluster`. The `ASOManagedCluster` approach was chosen because the `ManagedCluster` will eventually be deprecated. See [CAPZ ManagedCluster vs. ASOManagedCluster](https://capz.sigs.k8s.io/managed/managed#capzs-managed-cluster-versus-capzs-asomanaged-cluster).
ASO (azure service operator) requires Azure credentials to be defined in a …
> Add Azure AKS Cluster Template

- config/dev/openstack-managedcluster.yaml
- templates/cluster/openstack-standalone-cp/.helmignore
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/_helpers.tpl
- templates/cluster/openstack-standalone-cp/templates/cluster.yaml
- templates/cluster/openstack-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/openstack-standalone-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/openstack-standalone-cp/templates/machinedeployment.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackcluster.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-controlplane.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-worker.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/provider/hmc-templates/files/templates/openstack-standalone-cp-0-0-1.yaml
Resolves #592.
This PR introduces a Helm chart and associated templates to facilitate the deployment of standalone control plane on OpenStack within the Hybrid Multi-Cloud (HMC) platform. 
Local Run:
```
ka get machines
NAME                           CLUSTER         NODENAME                       PROVIDERID                                          PHASE     AGE     VERSION
openstack-dev-cp-0             openstack-dev   openstack-dev-cp-0             openstack:///b52ccc71-566b-4487-a0b8-64b2c08f0e5b   Running   8m29s   v1.30.5+k0s.0
openstack-dev-cp-1             openstack-dev   openstack-dev-cp-1             openstack:///4022efcb-da46-4a99-80f3-2eaf3681238e   Running   8m29s   v1.30.5+k0s.0
openstack-dev-cp-2             openstack-dev   openstack-dev-cp-2 …
```
> Add OpenStack standalone control plane Helm chart and templates

- Makefile
- cmd/main.go
- config/dev/openstack-credentials.yaml
- go.mod
- go.sum
- internal/controller/clusterdeployment_controller.go
- internal/credspropagation/azure.go
- internal/credspropagation/common.go
- internal/credspropagation/openstack.go
- internal/credspropagation/vsphere.go
- internal/webhook/clusterdeployment_webhook.go
Local Run:
```
ka get machines
NAME                           CLUSTER         NODENAME                       PROVIDERID                                          PHASE     AGE     VERSION
openstack-dev-cp-0             openstack-dev   openstack-dev-cp-0             openstack:///b52ccc71-566b-4487-a0b8-64b2c08f0e5b   Running   8m29s   v1.30.5+k0s.0
openstack-dev-cp-1             openstack-dev   openstack-dev-cp-1             openstack:///4022efcb-da46-4a99-80f3-2eaf3681238e   Running   8m29s   v1.30.5+k0s.0
openstack-dev-cp-2             openstack-dev   openstack-dev-cp-2             openstack:///87ae87e0-2ac5-4f06-b7ba-970d6dbcab3f   Running   8m29s   v1.30.5+k0s.0
openstack-dev-md-p27j6-6wfn4   openstack-dev   openstack-dev-md-p27j6-6wfn4 …
```
> Add OpenStack credential propagation support

- templates/provider/cluster-api/Chart.yaml
- templates/provider/cluster-api/templates/provider.yaml
- templates/provider/hmc-templates/files/release.yaml
- templates/provider/hmc-templates/files/templates/cluster-api.yaml
> Bump capi to 1.9.3

- config/dev/openstack-clusterdeployment.yaml
With the recent change in name for `ManagedCluster`, the files under config/dev was not updated with the latest `ClusterDeployment` name. This PR fixes it.
> Update ManagedCluster to ClusterDeployment for OpenStack dev file

- .golangci.yml
- Makefile
- internal/controller/clusterdeployment_controller.go
- internal/controller/clusterdeployment_controller_test.go
- internal/controller/management_controller_test.go
- internal/controller/multiclusterservice_controller_test.go
- internal/controller/suite_test.go
- internal/controller/template_controller_test.go
- internal/helm/actor.go
> managedcluster-controller tests

- Makefile
- hack/k0s-ag-image/Dockerfile
- hack/k0s-ag-image/default.conf
- scripts/bundle-images.sh
- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/vsphere-hosted-cp/values.schema.json
- templates/cluster/vsphere-hosted-cp/values.yaml
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/vsphere-standalone-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/vsphere-standalone-cp/values.schema.json
- templates/cluster/vsphere-standalone-cp/values.yaml
- templates/provider/hmc-templates/files/templates/vsphere-hosted-cp-0-0-4.yaml
- templates/provider/hmc-templates/files/templates/vsphere-standalone-cp-0-0-4.yaml
Resolves #702 
Still need to decide where to put k0s-image
> Fix k0s installation in airgap env

- docs/dev.md
This PR adds internal dev documentation for additional info on our e2e tests and CI workflows.
> Add e2e and CI docs

- docs/dev.md
- clarify provider setup, environment variables, and recommended image/flavor requirements.
- fix warnings raised by markdownlint.
Related code changes are in #695, #696, #697
> docs(openstack): add instructions for OpenStack provider on HMC

- templates/cluster/aws-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/aws-hosted-cp/values.schema.json
- templates/cluster/aws-hosted-cp/values.yaml
This PR adds the ability to set the management cluster name in the AWS hosted template. This is needed because of issue #788. Requires PR https://github.com/Mirantis/helm-charts/pull/2 to be merged and the resulting helm chart to be published. An upstream PR for the change to the chart has been created : https://github.com/kubernetes/cloud-provider-aws/pull/1085.
> Fix AWS hosted cluster template networking issue (fixes #788)

- api/v1alpha1/clusterdeployment_types.go
- internal/controller/clusterdeployment_controller.go
- templates/cluster/aws-eks/templates/cluster.yaml
- templates/cluster/aws-eks/values.yaml
- templates/cluster/aws-hosted-cp/templates/cluster.yaml
- templates/cluster/aws-hosted-cp/values.yaml
- templates/cluster/aws-standalone-cp/templates/cluster.yaml
- templates/cluster/aws-standalone-cp/values.yaml
- templates/cluster/azure-hosted-cp/templates/cluster.yaml
- templates/cluster/azure-hosted-cp/values.yaml
- templates/cluster/azure-standalone-cp/templates/cluster.yaml
- templates/cluster/azure-standalone-cp/values.yaml
- templates/cluster/vsphere-hosted-cp/templates/cluster.yaml
- templates/cluster/vsphere-hosted-cp/values.yaml
- templates/cluster/vsphere-standalone-cp/templates/cluster.yaml
- templates/cluster/vsphere-standalone-cp/values.yaml
Provide ability to add labels to the `Cluster` object created when installing a clusterTemplate by:
1. Adding `.Values.ClusterLabels` to all clusterTemplate helm charts.
2. Using `ManagedCluster`'s own labels via the HMC controller if none have been defined in `.Values.ClusterLabels`.
As can be seen from the output below, the `.metadata.labels` from `ManagedCluster` have been added to the `Cluster` object:
```sh
➜  ~ kubectl -n hmc-system get managedclusters.hmc.mirantis.com wali-dev-1 --show-labels
NAME         READY   STATUS                    LABELS
wali-dev-1   True    ManagedCluster is ready   labelA=A,labelB=B
➜  ~
➜  ~
➜  ~ kubectl -n hmc-system get cluster --show-labels                                
NAME         CLUSTERCLASS   PHASE         AGE   VERSION   LABELS
wali-dev-1 …
```
> Provide ability to add labels to `Cluster` object

- README.md
It's KCM.  This was legacy language.
> Remove Hybrid Container Cloud references

- config/dev/openstack-clusterdeployment.yaml
Without these default values, cluster provisioning will not proceed. The defaults provided here are used by OpenStackCluster, OpenStackMachine. 
This is similar to how the other providers are currently set up.
> Set default values for OpenStack resources 

- config/dev/adopted-clusterdeployment.yaml
- test/e2e/clusterdeployment/aws/aws.go
- test/e2e/clusterdeployment/clusterdeployment.go
- test/e2e/clusterdeployment/clusteridentity/clusteridentity.go
- test/e2e/clusterdeployment/constants.go
- test/e2e/clusterdeployment/providervalidator.go
- test/e2e/clusterdeployment/resources/adopted-cluster.yaml.tpl
- test/e2e/clusterdeployment/resources/aws-hosted-cp.yaml.tpl
- test/e2e/clusterdeployment/resources/aws-standalone-cp.yaml.tpl
- test/e2e/clusterdeployment/validate_deployed.go
- test/e2e/e2e_suite_test.go
- test/e2e/kubeclient/kubeclient.go
- test/e2e/provider_adopted_test.go
- test/e2e/provider_aws_test.go
- test/e2e/provider_azure_test.go
- test/e2e/provider_vsphere_test.go
This adds adopted cluster e2e tests to the suite. Also, I've ported in the various fixes around timing issues like waiting for the cluster templates to be valid and the credentials to be ready before creating deployments. Resolves #828, #339 and #871
> Implement adopted cluster e2e tests

- .github/workflows/build_test.yml
This is forcing tests to be always on main.
With actions approval it doesn't make much sense
> Remove second checkout for e2e tests workflow

- config/dev/eks-clusterdeployment.yaml
- templates/cluster/aws-eks/Chart.yaml
- templates/cluster/aws-eks/templates/awsmanagedcontrolplane.yaml
- templates/cluster/aws-eks/values.schema.json
- templates/cluster/aws-eks/values.yaml
- templates/provider/kcm-templates/files/templates/aws-eks-0-0-4.yaml
- test/e2e/clusterdeployment/clusterdeployment.go
- test/e2e/clusterdeployment/providervalidator.go
- test/e2e/clusterdeployment/resources/aws-eks.yaml.tpl
- test/e2e/clusterdeployment/validate_deleted.go
- test/e2e/clusterdeployment/validate_deployed.go
- test/e2e/e2e_suite_test.go
- test/e2e/kubeclient/kubeclient.go
- test/e2e/provider_adopted_test.go
- test/e2e/provider_aws_test.go
- test/e2e/provider_azure_test.go
- test/e2e/provider_vsphere_test.go
This PR introduces the following changes:
1. Added e2e testing to verify the successful deployment of an EKS cluster
2. Enhanced the EKS template to allow deployment of additional add-ons
3. Configured the CSI driver add-on to be enabled by default
4. Workaround for #907 is applied on EKS clusters (created by e2e tests only)
E2E testing for EKS deployments is enabled by default and integrated into the AWS provider testing suite. At this time, hosted cluster deployments are not supported for EKS clusters.
Testing Scenario:
1. Deploy an EKS cluster using the default simple configuration
2. Apply workaround for #907 for the MachineDeployment
3. Verify the deployment of all related objects
4. Verify the CSI driver
5. Verify the CCM
P.S. The testing scenario is intentionally kept simple, …
> Add EKS e2e testing

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-controlplane.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-0-0-3.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
This PR updates `controlplane` to `controlPlane` in OpenStack templates to stay consistent with the naming.
It also adds OpenStackCluster to kcm-manager-role.
> update controlplane to controlPlane and add openstackcluster to role

- internal/webhook/template_webhook.go
- internal/webhook/template_webhook_test.go
Currently, the template cannot be deleted if the chain that owns it no longer exists, but is still present in the `OwnerReferences` list as the deletion request is blocked by the admission webhook. As a result, the garbage collector is unable to properly remove the managed template.
> Do not block template removal if all the owners do not exist

- test/e2e/clusterdeployment/constants.go
- test/e2e/clusterdeployment/resources/adopted-cluster.yaml.tpl
- test/e2e/clusterdeployment/resources/aws-standalone-cp.yaml.tpl
- test/e2e/clusterdeployment/servicevalidator.go
- test/e2e/clusterdeployment/validate_deployed.go
- test/e2e/kubeclient/kubeclient.go
- test/e2e/multi_provider_test.go
- test/e2e/provider_aws_test.go
- Add test of deploying service using ServiceTemplate included into ClusterDeployment
Fixes: #849 #850
> e2e test of managed service deployment

- PROJECT
- api/v1alpha1/indexers.go
- api/v1alpha1/management_backup_types.go
- internal/controller/accessmanagement_controller.go
- internal/controller/accessmanagement_controller_test.go
- internal/controller/backup/reconcile.go
- internal/controller/backup/reconcile_test.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/credential_controller.go
- internal/controller/management_backup_controller.go
- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- internal/controller/multiclusterservice_controller.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/controller/templatechain_controller.go
- internal/utils/label.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_managementbackups.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
- test/objects/accessmanagement/accessmanagement.go
* add new flag to scheduled backups to enable autobackups during
upgrades
* create auto backups if velero is installed and upgrade is progressing
* block upgrades until all of the backups are completed
* new indexer for backups with autoupgrades
* new RBAC permission for apps/deployments
* update signature of func adding kcm component labels
* put mgmtbackups into backups
* reconcile mgmtbackups statuses after restoration
Closes #864
> Create backups on release upgrade

- api/v1alpha1/multiclusterservice_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/multiclusterservice_controller.go
- internal/sveltos/profile.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_multiclusterservices.yaml
This PR exposes the drift correction functionality of Sveltos via the `ClusterDeployment` and `MultiClusterService` objects by:
1. Introducing `.spec.serviceSpec.syncMode`: Sveltos will automatically deploy a drift-detection-manager on the managed cluster by setting this to `ContinuousWithDriftDetection`.
2. Introducing `.spec.serviceSpec.driftExclusions`: To exclude any particular field of an object from drift detection/correction.
3. Introducing `.spec.serviceSpec.ignoreDrift`: To exclude any object as a whole from drift detection/correction.
I created a new managed cluster with the following `ClusterDeployment`:
```yaml
kind: ClusterDeployment
metadata:
name: wali-dev-1
spec:
config:
clusterIdentity:
name: …
```
> Enable Sveltos Drift Detection

- internal/controller/backup/reconcile_test.go
- internal/webhook/management_webhook.go
- internal/webhook/management_webhook_test.go
- test/objects/template/template.go
This PR adds validation for CAPI provider contracts during `Management` updates. It prevents updates to provider templates currently in use if the updated provider contract version is incompatible with one or more existing cluster deployments.
Closes #684
> Validate CAPI contracts in-used by deployments on management update

- api/v1alpha1/clusterdeployment_types.go
- api/v1alpha1/common.go
- api/v1alpha1/management_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_managements.yaml
This PR introduces a `Ready` Condition and new printer columns in the Management CRD making it possible to look at the readiness of Management object at a glance along with release version. 
✅  Unit Tests
✅  Fixes #807 
Kubectl gets the following:
```bash
kubeclt get management -w
NAME   READY   RELEASE     AGE
kcm    False       kcm-0-0-7   22s
kcm    False       kcm-0-0-7   3m54s
kcm    False       kcm-0-0-7   4m24s
kcm    True        kcm-0-0-7   4m34s
```
<details>
<summary>Click to check an example Status generated</summary>
```yaml
status:
availableProviders:
- bootstrap-k0sproject-k0smotron
- control-plane-k0sproject-k0smotron
- infrastructure-aws
- infrastructure-azure
- infrastructure-internal
- infrastructure-k0sproject-k0smotron
- infrastructure-openstack
- …
```
> add Ready condition to Management resources

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-controlplane.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-worker.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-0-0-6.yaml
Expose rootVolume option in Openstack standalone control plane cluster template.
Resolves #965
> Expose configuration options for Openstack volumes in the template

- config/dev/aks-credentials.yaml
Currently, its name matches the ConfigMap from `config/dev/azure-credentials.yaml`. If I run `make dev-azure-creds` followed by make `dev-aks-creds`, the Azure credentials ConfigMap gets overwritten with the AKS credentials (which is empty since no creds propagation is required).
> Fix dev AKS credentials configmap name

- internal/controller/clusterdeployment_controller.go
- internal/webhook/clusterdeployment_webhook.go
- internal/webhook/clusterdeployment_webhook_test.go
- test/objects/clusterdeployment/clusterdeployment.go
Disallow cross-namespace references in ClusterDeployment because it is namespace scoped. If there is a reference to another namespace and the validation webhooks are disabled, the kcm-controller will return an error and it will show up in the status for example:
```yaml
kind: ClusterDeployment
metadata:
. . .
name: wali-dev-1
. . .
spec:
. . .
serviceSpec:
priority: 100
services:
- name: kyverno
namespace: kyverno
template: kyverno-3-2-6
valuesFrom:
- kind: Secret
name: my-creds
namespace: testns1
stopOnConflict: false
syncMode: Continuous
template: aws-standalone-cp-0-0-7
status:
conditions:
- lastTransitionTime: "2025-01-30T17:45:12Z"
message: Template is valid
reason: Succeeded
status: "True"
type: TemplateReady
- …
```
> Disallow cross-namespace references in ClusterDeployment

- .github/workflows/build_test.yml
This PR updates the `authorize` job to retrieve the testing configuration from the approval comment. The comment should be provided during the approval process for deployment in the `external` environment.
* The comment must contain valid YAML content representing the testing configuration.
* If the comment is empty, the default testing configuration will be used, which deploys a single AWS standalone cluster.
* If the comment contains invalid YAML, an error will occur and the job will fail.
Below is an example that demonstrates how this process should work:
https://github.com/user-attachments/assets/84971961-4dcc-4912-aa22-12ad030d5254
Closes #642
> Support for providing a testing configuration to the workflow

- config/dev/kcm_values.yaml
- internal/controller/backup/periodic_test.go
- internal/controller/template_controller.go
* add mgmt watcher to clustertemplates to queue templates if providers have been removed or added
* turn on dev logger in dev config
* unrelated micro fix trying to address periodic runner tests sporadic panic
Closes #954
> Add mgmt watcher to clustertemplates

- cmd/main.go
- config/dev/kcm_values.yaml
- internal/controller/release_controller.go
- internal/utils/release.go
- internal/utils/release_test.go
- templates/provider/kcm/templates/deployment.yaml
- templates/provider/kcm/values.schema.json
- templates/provider/kcm/values.yaml
* setup pprof handler
* turn off by default
* enable pprof in dev config
* add rfc1123 name validation
* added some unit tests to cover semver
Since `pprof` is disabled by default there is no reason to provide extra `ports` entry along with the `Service` resource for the port.
Closes #773
Closes #775
> Add ability to setup `pprof` and enhance `Release` name generation checks

- internal/controller/management_controller.go
* Fix panic on `enableAdditionalComponents` when `spec.core` is unset
* Update `getWrappedComponents` to handle the case when `spec.core` is unset without breaking
Closes #939
> Fix panic when spec.core is unset in custom Management

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-controlplane.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-worker.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-0-1-1.yaml
Add support for additional block devices for openstack cluster machines. It is required for storage solutions.
Implements https://github.com/k0rdent/kcm/issues/1054
> Add support for additionalBlockDevices in openstack-standalone-cp

- api/v1alpha1/clusterdeployment_types.go
- cmd/main.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/suite_test.go
- templates/cluster/adopted-cluster/templates/sveltoscluster.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
Simple change to add the sveltos cluster status to the clusterdeployment conditions for adopted clusters. This fixes issue #953.
> Add sveltos cluster status to the clusterdeployment conditions

- .github/workflows/build_test.yml
When the `test e2e` label is set, the provider tests are triggered, which already validate the controller. A separate controller test is redundant.
> Do not trigger separate controller test on PRs with `test e2e` label

- Makefile
- cmd/main.go
- go.mod
- internal/controller/accessmanagement_controller.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/credential_controller.go
- internal/controller/management_backup_controller.go
- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- internal/controller/multiclusterservice_controller.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/controller/templatechain_controller.go
- internal/utils/ratelimit/ratelimit.go
* custom per-item fast-slow ratelimiter for all of the controllers
* chores: requeue period as a dedicated field in corresponding controllers
* update envtest k8s version to 1.32.0
Closes #1081
> Add custom ratelimiter

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-0-1-4.yaml
Sometimes node deployment could be slow therefore openstack ccm sets providerID without region in format `openstack:///<instanceID>` instead of `openstack://<region>/<instanceID>`. Enable OS_CCM_REGIONAL to openstack ccm always set region to providerID.
-----
Fixes https://github.com/k0rdent/kcm/issues/1077
> capo: Fix missing region in providerID on cluster nodes

- Makefile
- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/cluster-api-provider-openstack/templates/orc-1-0-0.yaml
- templates/provider/cluster-api-provider-openstack/values.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
Fixes https://github.com/k0rdent/kcm/issues/1090
-----
CAPO v0.12.0 misses openstack-resource-controller with all required objects and CRDs. Add orc v1.0.0 `install.yaml` as a template to capo chart.
> capo: Add orc v1.0.0 file with all required objects

- cmd/main.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
Fixed an issue where the provider templates depend on the management object and the management object depends on the provider templates making it impossible to deploy kcm with the create management flag set to false.
Resolves issue https://github.com/k0rdent/kcm/issues/940
> Fix issue with installation with create management flag set to false

- Makefile
- config/dev/remote-clusterdeployment.yaml
- config/dev/remote-credentials.yaml
- templates/cluster/remote-cluster/.helmignore
- templates/cluster/remote-cluster/Chart.yaml
- templates/cluster/remote-cluster/templates/_helpers.tpl
- templates/cluster/remote-cluster/templates/cluster.yaml
- templates/cluster/remote-cluster/templates/k0smotroncontrolplane.yaml
- templates/cluster/remote-cluster/templates/machines.yaml
- templates/cluster/remote-cluster/templates/remotecluster.yaml
- templates/cluster/remote-cluster/values.schema.json
- templates/cluster/remote-cluster/values.yaml
- templates/provider/kcm-templates/files/templates/remote-cluster-0-1-0.yaml
This PR adds a new cluster template for provisioning remote servers, corresponding Makefile targets, and dev config examples.
Closes #1085
Closes #1112
> Add Remote Server cluster template

- internal/webhook/clusterdeployment_webhook.go
- internal/webhook/clusterdeployment_webhook_test.go
- templates/cluster/remote-cluster/templates/cluster.yaml
1. Adjust admission validation for the k0smotron infrastructure provider
2. Fix incorrect control plane ref in the `remote-server` template
Closes #1113
> Adjust admission validation for the k0smotron infrastructure provider

- README.md
- api/v1alpha1/clusterdeployment_types.go
- api/v1alpha1/multiclusterservice_types.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/multiclusterservice_controller.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_multiclusterservices.yaml
* add number of ready services condition to `cld`/`mcs` statuses
* add number of ready clusters condition to `mcs` status
* print the new conditions in custom columns
* adjust `cld` print columns
* calculate `cld`/`mcs` readiness based on services readiness
* calculate `mcs` readiness based on selected clusters readiness
* add short name to `mcs` resource
Closes #1028 
Closes #1027
Closes #813
> Adjust `cld` and `mcs` statuses

- internal/controller/clusterdeployment_controller.go
- internal/controller/multiclusterservice_controller.go
This simple fix resolves an issue where the services aren't removed by sveltos when the services list is empty / missing in the cluster deployment after previously being deployed. The fix is to remove the sveltos profile which triggers the adon controller to un-deploy all the helm charts associated with the profile. 
Testing performed:
1. Create cluster deployment with nginx/kyverno installed
2. Remove nginx and apply the cluster deployment yaml
3. nginx is uninstalled as expected
4. Remove kyverno and apply the yaml file again and now kyverno is uninstalled. Previous to this fix kyverno would have remained.
Closes #1132
> Fix- When removing all services from a cluster deployment the services remain deployed

- templates/cluster/gcp-hosted-cp/.helmignore
- templates/cluster/gcp-hosted-cp/Chart.yaml
- templates/cluster/gcp-hosted-cp/templates/_helpers.tpl
- templates/cluster/gcp-hosted-cp/templates/cluster.yaml
- templates/cluster/gcp-hosted-cp/templates/gcpcluster.yaml
- templates/cluster/gcp-hosted-cp/templates/gcpmachinetemplate.yaml
- templates/cluster/gcp-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/gcp-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/gcp-hosted-cp/templates/machinedeployment.yaml
- templates/cluster/gcp-hosted-cp/values.schema.json
- templates/cluster/gcp-hosted-cp/values.yaml
- templates/provider/kcm-templates/files/templates/gcp-hosted-cp-0-1-0.yaml
This PR contains the cluster template for the hosted GCP cluster.
It does not contain a CSI component yet. It'll be enabled in the follow-up PR once https://github.com/Mirantis/helm-charts/pull/4 is landed and the CSI helm chart is published.
Closes #1149
> Add GCP hosted cluster template

- cmd/main.go
Add leader-election-namespace flag for out-of-cluster debugging
When running the controller outside a cluster (e.g., for debugging), the leader election namespace cannot be automatically determined. This change adds a `--leader-election-namespace` flag to explicitly specify the namespace, making local debugging possible while maintaining the default in-cluster behavior unchanged.
The flag is optional and only needed for out-of-cluster scenarios such as while running debuggers.
> add leaderElectionNamespace flag in main.go - helps with debugging 

- cmd/main.go
- internal/controller/management_controller.go
* during the calculation of mgmt status, ignore INFO severity conditions from cluster-api operator resources
* might be reverted or removed after the upstream issue (https://github.com/kubernetes-sigs/cluster-api-operator/issues/755) is addressed
Closes #1221
> Ignore CAPO info conditions in mgmt status

- internal/controller/clusterdeployment_controller.go
- internal/controller/multiclusterservice_controller.go
- internal/controller/template_controller.go
- internal/metrics/metrics.go
Add a metric to track currently invalid templates. Example:
```
kcm_template_invalidity{template_kind="ClusterTemplate",template_name="aws-hosted-cp-0-1-5",template_namespace="kcm-system"} 1
kcm_template_invalidity{template_kind="ClusterTemplate",template_name="aws-standalone-cp-0-1-5",template_namespace="kcm-system"} 1
kcm_template_invalidity{template_kind="ClusterTemplate",template_name="azure-aks-0-1-1",template_namespace="kcm-system"} 1
kcm_template_invalidity{template_kind="ClusterTemplate",template_name="azure-hosted-cp-0-1-5",template_namespace="kcm-system"} 1
kcm_template_invalidity{template_kind="ClusterTemplate",template_name="azure-standalone-cp-0-1-5",template_namespace="kcm-system"} 1
kcm_template_invalidity{template_kind="ClusterTemplate",template_name="docker-hosted-cp-0-1-3 …
```
> Add template invalidity metric

- test/e2e/provider_adopted_test.go
From https://github.com/k0rdent/kcm/actions/runs/14056507665/job/39357435892
```
Adopted Cluster Templates [BeforeAll] should work with an Adopted cluster provider [provider:cloud, provider:adopted]
[BeforeAll] /home/runner/work/kcm/kcm/test/e2e/provider_adopted_test.go:48
[It] /home/runner/work/kcm/kcm/test/e2e/provider_adopted_test.go:89
[PANICKED] Test Panicked
In [BeforeAll] at: /opt/hostedtoolcache/go/1.23.7/x64/src/runtime/panic.go:262 @ 03/25/25 10:14:43.757
```
> Fix panic in adopted e2e testing

- config/dev/docker-clusterdeployment.yaml
- templates/cluster/docker-hosted-cp/Chart.yaml
- templates/cluster/docker-hosted-cp/values.yaml
- templates/provider/kcm-templates/files/templates/docker-hosted-cp-0-1-4.yaml
Reason: https://github.com/k0rdent/kcm/pull/1057#issuecomment-2668629616
> Revert k0s version to 1.32.1 for docker cluster template

- internal/controller/management_controller.go
Cherry Pick #1281
* Do not drop unused kcm templates HelmReleases
* Call releases list before the loop
Closes #1279
> Do not drop unused kcm templates HelmReleases

- internal/webhook/template_webhook.go
Improve warning message to make it more verbose
```
W0327 16:24:07.538608    5186 warnings.go:70] The kof-storage-0-2-0-rc2 ServiceTemplate object can't be removed if MultiClusterService objects [kof-regional-cluster] referencing it still exist
Error: UPGRADE FAILED: pre-upgrade hooks failed: admission webhook "validation.servicetemplate.k0rdent.mirantis.com" denied the request: template deletion is forbidden
```
instead of just
```
W0327 15:45:04.626916   91612 warnings.go:70] The ServiceTemplate object can't be removed if MultiClusterService objects referencing it still exist
Error: UPGRADE FAILED: pre-upgrade hooks failed: admission webhook "validation.servicetemplate.k0rdent.mirantis.com" denied the request: template deletion is forbidden
```
> Template webhook verbose warning

- PROJECT
- api/v1alpha1/management_types.go
- cmd/main.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/webhook/accessmanagement_webhook.go
- internal/webhook/multiclusterservice_webhook.go
- internal/webhook/templatechain_webhook.go
- templates/provider/kcm/templates/deployment.yaml
- templates/provider/kcm/values.yaml
* trigger mgmt on release create/delete
* set not ready to mgmt if release is not found
* do not reconcile mgmt if release is not found
* fix admission wh disabled by default
* release ctrl sets release owner ref to kcm-templates
helm release in order to create a new one when
a new release is created; this action does not remove
other components since the mgmt will not be
reconciled when the release object is absent
* chore: kubebuilder project and redundant defaulters
There is nothing to do with the webhook validations reconciliation. Here goes the same idea as in the #1288: there are currently no finalizers for the `releases` CR and hence it does not make much sense to fully block the reconciliation of a `Release` object and force a user to delete it.
To properly address (re)creation of …
> Handle `Release` object delete request

- config/dev/azure-credentials.yaml
* Related to https://github.com/k0rdent/kcm/issues/1118
* We already have a default `StorageClass` added to the docs [here](https://docs.k0rdent.io/v0.2.0/quickstarts/quickstart-2-azure/#create-the-configmap-resource-template-object).
* This PR adds it to `make dev-azure-creds` too - for development purposes only, e.g. https://github.com/k0rdent/kof/issues/36
* It does not change cluster template, so there is no conflict with [this comment](https://github.com/k0rdent/kcm/issues/1118#issuecomment-2682078575).
> Add `StorageClass` to `make dev-azure-creds`

- .golangci.yml
- Makefile
- internal/controller/credential_controller.go
- internal/controller/management_backup_controller.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/controller/servicetemplate_controller.go
- internal/controller/template_controller.go
- internal/webhook/management_webhook.go
- internal/webhook/template_webhook.go
* migrate linter from v1 to v2
* address a new QF from the statickcheck
* amend the config adding rules for the testifylint
* amend the config adding issues, severity, output sections
> Golangci-lint@v2

- api/v1alpha1/credential_types.go
- cmd/main.go
- config/dev/kcm_values.yaml
- internal/controller/clusterdeployment_controller.go
- internal/controller/clusterdeployment_controller_test.go
- internal/controller/management_controller.go
- internal/controller/multiclusterservice_controller.go
- internal/utils/validation/cd.go
- internal/utils/validation/cluster_template.go
- internal/webhook/clusterdeployment_webhook.go
- internal/webhook/clusterdeployment_webhook_test.go
* add servicetemplates watcher to cld controller
and mcs controller if validations are turned off
* add clustertemplate watcher to cld controller
if validations are turned off
* mcs controller reconciles validations if they are turned off
* cld controller reconciles validations if they are turned off
- k8s compatibility failure results in template ready cond
- credentials validation failure results in creds ready cond
* cld controller: if validation WH is turned off and validation
has failed it won't be retriggered due to watchers
* cld controller: if validation WH is turned off and cluster template
is not valid it won't be retriggered due to clustertemplate watcher
* fixed always-ready creds condition in cld
NOTES:
* the mutations are not reconciled
* the upgrade sequence validation is …
> feat: ClusterDeployment reconciles validations

- api/v1alpha1/clusterdeployment_types.go
- cmd/main.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/clusterdeployment_controller_test.go
- internal/utils/status/status.go
Get CAPI v1beta2 condition summary from the Cluster object instead of getting old conditions from MachineDeployments and Cluster objects. Conditions from Cluster objects (`ControlPlaneInitialized`, `ControlPlaneReady`, `InfrastructureReady`) and MachineDeployment (`Available`) have been replaced with similar v1beta2 Cluster conditions.
When the cluster is deploying:
```
- lastTransitionTime: "2025-04-09T12:09:42Z"
message: |-
* ControlPlaneInitialized: Control plane not yet initialized
* ControlPlaneAvailable: K0sControlPlane status.ready is false
* WorkersAvailable:
* MachineDeployment gcp-ekaz-md: 0 available replicas, at least 1 required (spec.strategy.rollout.maxUnavailable is 0, spec.replicas is 1)
* RemoteConnectionProbe: Remote connection probe failed
reason: IssuesReported
status: …
```
> feat: Rework CAPI conditions aggregator for ClusterDeployment

- api/v1alpha1/management_types.go
- internal/controller/management_controller.go
This PR adds labels to the "mgmt" `sveltoscluster`, which is used to self-manage the management/mothership cluster. Once the labels are added, we can then use a `MultiClusterService` object to deploy services on the management cluster.
Documentation for users to be added in https://github.com/k0rdent/kcm/issues/1305.
We can see the labels added to the "mgmt" cluster:
```sh
➜  ~ kubectl -n mgmt get sveltoscluster mgmt --show-labels
NAME   READY   VERSION   LABELS
mgmt   true    v1.32.2   k0rdent.mirantis.com/management-cluster=true,projectsveltos.io/k8s-version=v1.32.2,sveltos-agent=present
```
Now we can deploy "myapp" service using the following `MultiClusterService`:
```yaml
kind: MultiClusterService
metadata:
name: myapp
spec:
clusterSelector: …
```
> feat: Allow self management of mothership cluster via Sveltos

- PROJECT
- api/v1alpha1/compatibility_contract.go
- api/v1alpha1/management_types.go
- internal/controller/management_controller.go
- internal/utils/validation/mgmt.go
- internal/utils/validation/provider_template.go
- internal/webhook/management_webhook.go
- internal/webhook/management_webhook_test.go
- templates/provider/kcm/templates/webhooks.yaml
* if validations wh is disabled, mgmt ctrl watches `releases`
updates and `providertemplates` valid updates
* if validations wh is disabled, mgmt ctrl reconciles release
readiness validation and providers' capi contracts compatibility
* removed unused management mutations
* if validations wh is disabled, mgmt ctrl
blocks deletion if clusterdeployment objects
exist
NOTE: validating component removal is not possible hence there is
no such validation within the management ctrl
Fixes #1235
> feat: Management reconciles validations

- templates/provider/kcm/templates/rbac/controller/roles.yaml
> fix: add missing RBAC for clustertemplatechain/status

- api/v1alpha1/clusterdeployment_types.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/management_controller.go
- internal/controller/multiclusterservice_controller.go
* fix cld controller deletion logic to avoid dropping the finalizer before the rest of the cleanup
* small refactor in the cld ctrl
If admission validation webhook is turned off:
* mgmt ctrl processes absent ProviderTemplates and does not retrigger
* mcs ctrl processes absent ServiceTemplates and does not retrigger
* cld ctrl processes absent ServiceTemplates and ClusterTemplates and does not retrigger
* fix incorrect requests in the servicetemplates watcher in the mcs ctrl
* cld ctrl now watches creation of Cluster and ServiceTemplates
* cld ctrl does not proceed deletion if ClusterTemplate is missing stopping the finalizer deletion
Fixes #1240
> improvement: process absent *Templates

- .github/workflows/post-merge-push.yaml
This PR adds the `arm64` platform to the post-merge job to build a CI controller image for arm64 as well.
Related task: https://github.com/k0rdent/kcm/pull/1381
> Add arm64 platform to post-merge push job

- Makefile
- api/v1alpha1/common.go
- cmd/main.go
- go.mod
- internal/controller/accessmanagement_controller.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/clusterdeployment_controller_test.go
- internal/controller/credential_controller.go
- internal/controller/management_controller.go
- internal/controller/multiclusterservice_controller.go
- internal/controller/release_controller.go
- internal/controller/templatechain_controller.go
- internal/record/recorder.go
- internal/utils/conditions/capi.go
- templates/provider/kcm/templates/rbac/controller/roles.yaml
This PR introduces event generation for key management and ClusterDeployment operations, including:
1. K0rdent installation and uninstallation
2. Provider addition and deletion
3. Provider configuration updates
4. Reconciliation failures
5. ClusterDeployment config validation issues
6. ClusterDeployment-related HelmRelease creation/update
7. ClusterDeployment deletion
etc.
Also, contains:
1. Several functions refactoring to reduce cyclomatic complexity.
2. ClusterDeployment deletion conditions aggregator to report deletion issues in events
Note: To emit proper events that will be helpful during debugging, the cluster deployment reconciler should be refactored, and the CAPI conditions aggregation should be reworked (#1366). This will be done in follow-up PRs. 
Closes #1339 
Closes #1341
> feat: emit events for Management and ClusterDeployment operations

- Makefile
This PR changes the default value for the `CLUSTER_NAME_SUFFIX` to better understand the names of clusters in the case of default values.
The previous version allowed the value to be `<provider>-dev`, and the updatedversion  sets the default value to the `<provider>-<current-logged-user>-<date>`, where `<date>` is in format `dd-mm-yyyy`
> chore: change Make default cluster suffix

- config/dev/azure-clusterdeployment.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/templates/k0scontrolplane.yaml
- templates/provider/kcm-templates/files/templates/azure-hosted-cp-0-2-2.yaml
- templates/provider/kcm-templates/files/templates/azure-standalone-cp-0-2-2.yaml
After upgrading k0s to v1.32.3, the Azure Cloud Controller Manager fails to deploy due to a limitation in the Helm chart, which determines the CCM image version. It does not currently handle Kubernetes version 1.32: https://github.com/Mirantis/helm-charts/blob/main/mirantis/cloud-provider-azure/templates/cloud-provider-azure.yaml#L22
As a result, `.cloudProviderAzureVersion` remains unset, which causes the generated image path to be empty: https://github.com/Mirantis/helm-charts/blob/main/mirantis/cloud-provider-azure/templates/_image.tpl#L7
When the imageTag is specified, the image path is generated properly.
Fixes #1420
> fix: explicitly specify azure ccm imageTag

- api/v1alpha1/multiclusterservice_types.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/multiclusterservice_controller.go
- internal/sveltos/status.go
This PR introduces the following events:
```
1. ServicesReferencesValidationSucceeded
2. ServicesReferencesValidationFailed
3. SveltosProfileReady
4. SveltosProfileNotReady
5. SveltosClusterProfileReady
6. SveltosClusterProfileNotReady
7. FetchServicesStatusSuccess
8. FetchServicesStatusFailed
9. SveltosHelmReleaseReady
10. SveltosHelmReleaseNotReady
11. SveltosFeatureReady
12. SveltosFeatureNotReady
```
The following output shows that the status `ClusterDeployment` is being reported correctly:
```sh
➜  ~ kubectl -n kcm-system get clusterdeployment wali-dev-1 -o yaml    
kind: ClusterDeployment
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"k0rdent.mirantis.com/v1alpha1","kind":"ClusterDeployment","metadat …
```
> feat: Emit events for services

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-controlplane.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-worker.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-0-2-2.yaml
This patch replaces `sshPublicKey` in template values with `sshKeyName`
also used by upstream capi provider as well as bastion in this template.
values.schema.json now marks `sshPublickKey` as deprecated
By utilizing if-else block in template this change is backwards compatible
still allowing for use of `sshPublicKey` which might be needed for 
example when upgrading from 0-1-0 to 0-2-0
> fix(openstack-standalone-cp): make ssh config more uniform

- api/v1alpha1/indexers.go
- api/v1alpha1/pluggableprovider_types.go
- internal/controller/clusterdeployment_controller.go
- internal/utils/validation/cd.go
- internal/webhook/clusterdeployment_webhook_test.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_pluggableproviders.yaml
There was an inconsistency in the infrastructure providers' naming
(for example, searched for `infrastructure-aws` in one place and `aws` in another),
which breaks the removal of the blocking finalizer from the ClusterDeployment.
Now, the full provider name with the infrastructure prefix is being used.
Also, added an indexer for the PluggableProvider object to fetch all the exposed infrastructure providers.
Fixes #1438
> fix: unify infrastructure providers naming

- internal/controller/management_controller.go
- internal/controller/pluggableprovider_controller.go
- internal/utils/validation/mgmt.go
- templates/provider/kcm/templates/rbac/controller/roles.yaml
- templates/provider/kcm/templates/rbac/user-facing/pluggableproviders-editor.yaml
- templates/provider/kcm/templates/rbac/user-facing/pluggableproviders-viewer.yaml
PR Reworks `PluggableProvider` controller reconcile by adding additional watchers for `ProviderTemplate` and `Management` object update events.
> fix: Rework `PluggableProvider` controller reconcile

- README.md
prior information should be provided before the command is issued.
> docs: Fix prior information

- README.md
- templates/provider/kcm-templates/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
This PR includes the following changes:
1. Updates the KCM version in the Release object within the `kcm-templates` helm chart
2. Bump kcm and kcm-templates to the 0.3.0 version
3. Updates README.md to reflect the 0.3.0 release
> chore: update the Release, helm charts and README.md with the 0.3.0 release

- Makefile
- api/v1alpha1/management_types.go
- api/v1alpha1/providerinterface_types.go
- api/v1beta1/management_types.go
- api/v1beta1/providerinterface_types.go
- templates/provider/cluster-api-provider-openstack/Chart.yaml
- templates/provider/cluster-api-provider-openstack/templates/orc-2-1-0.yaml
- templates/provider/cluster-api-provider-openstack/values.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-openstack.yaml
* bump OpenStack ORC resources to v2.1.0
* preserve the v1.0.0 manifest for bw-comp
* pin ORC version in the Makefile
* bump CAPI OS provider version accordingly
* small field alignments at ProviderInterface
and Management API types (alpha,beta)
> chore: bump openstack ORC to 2.1.0

- Makefile
Treat any failed pull (including 403 or other errors) as if the chart does not exist, and always attempt to push it.
Currently, pull errors like 403 Forbidden are silently ignored and incorrectly interpreted as if the chart already exists in the repository. This prevents charts from being pushed when they actually should be.
> fix: Rework the helm-push Makefile target

- .github/actions/push-public/action.yml
- .github/workflows/build_test.yml
This PR includes the following changes:
1. Separate the `Lint and Unit Test` from the `Build Artifacts` jobs
2. Always run the `Lint and Unit Test` job
3. Move public artifacts build to the cloud and on-prem testing, and trigger it only in case the authorized job has been approved and the `PUBLIC_REPO` variable is set to true (which is required for the hosted deployments).
Partially verified on my forked repo. 
Fixes #1529
> ci: Fix public artifacts publishing in case hosted e2e is enabled

- .github/workflows/build_test.yml
It was accidentally renamed to k0rdent in one of the previous PRs.
> ci: Change the module name to uppercase

- internal/controller/release_controller.go
Explicitly set TypeMeta to sourcev1.HelmChart objects during the setup of KCM Templates
Fixes #1531
> chore: add helmcharts typemeta explicitly

- config/dev/gcp-clusterdeployment.yaml
- templates/cluster/gcp-hosted-cp/Chart.yaml
- templates/cluster/gcp-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/gcp-standalone-cp/Chart.yaml
- templates/cluster/gcp-standalone-cp/templates/k0scontrolplane.yaml
- templates/provider/kcm-templates/files/templates/gcp-hosted-cp-1-0-1.yaml
- templates/provider/kcm-templates/files/templates/gcp-standalone-cp-1-0-1.yaml
This PR configures the internal GCP CCM arguments with `--configure-cloud-routes=false` to fix an issue related to ClusterDeployment stuck deletion.
The fix prevents GCP CCM from creating `kubernetes-*` routes tied to VM instances which is redundant for our network setup.
Closes #1476
> fix: Set configure-cloud-routes=false in gcp ccm parameters

- config/dev/gke-clusterdeployment.yaml
- templates/cluster/gcp-gke/Chart.yaml
- templates/cluster/gcp-gke/templates/gcpmanagedcontrolplane.yaml
- templates/cluster/gcp-gke/values.schema.json
- templates/cluster/gcp-gke/values.yaml
- templates/provider/cluster-api-provider-gcp/Chart.yaml
- templates/provider/cluster-api-provider-gcp/templates/provider.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-gcp.yaml
- templates/provider/kcm-templates/files/templates/gcp-gke-1-0-1.yaml
This PR updates Cluster API Provider GCP to 1.9.0 and updates the `gcp-gke` cluster template to explicitly set the `spec.version` field in the `GCPManagedControlPlane` resource, as recommended in the [CAPG 1.9.0 release notes](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/releases/tag/v1.9.0).
Verification:
1. K0rdent upgrade from `1.0.0` to the latest version using an existing `1.0.0` GKE cluster completed successfully with no manual intervention required.
2. GKE cluster upgrade from gcp-gke `1.0.0` to `1.0.1` was verified with no issues.
Fixes #1542
> chore: Bump CAPG to 1.9.0

- internal/controller/servicetemplate_controller.go
- internal/controller/template_controller.go
Fixes https://github.com/k0rdent/kcm/issues/1467.
This issue in ServiceTemplates installed from https://catalog.k0rdent.io happened because the helm charts for the services in catalog are actually wrappers for the actual app.
Installed the ServiceTemplate `ingress-nginx-4-11-3` via the catalog:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
name: k0rdent-catalog
labels:
k0rdent.mirantis.com/managed: "true"
spec:
insecure: true
interval: 10m0s
provider: generic
type: oci
url: oci://ghcr.io/k0rdent/kcm/charts
---
kind: ServiceTemplate
metadata:
name: ingress-nginx-4-11-3
annotations:
helm.sh/resource-policy: keep
spec:
helm:
chartSpec:
chart: ingress-nginx
version: 4.11.3
interval: 10m0s …
```
> fix: helm values for servicetemplates not showing in status.config

- .github/workflows/ai-codereview.yml
Sets timeout for the AI-Review WF and forces to be canceled if new commits / rebases arrive
> ci: aireview timeout + concurrency cancel

- .github/workflows/ai-codereview.yml
- .github/workflows/build_test.yml
- .github/workflows/post-merge-push.yaml
- .github/workflows/release.yml
- .github/workflows/stale.yaml
- .github/workflows/triage.yaml
Grab only merge commit hash instead of the whole response from getting a PR.
Removed redundant jobs output from the CI WF.
Format and name all of the jobs/WFs.
Fixes #1550
> ci: simplify fetching PR reference

- Makefile
- README.md
- config/dev/aws-clusterdeployment.yaml
- templates/cluster/aws-eks/Chart.yaml
- templates/cluster/aws-eks/templates/awsmachinetemplate-worker.yaml
- templates/cluster/aws-eks/values.schema.json
- templates/cluster/aws-eks/values.yaml
- templates/cluster/aws-hosted-cp/Chart.yaml
- templates/cluster/aws-hosted-cp/templates/awsmachinetemplate.yaml
- templates/cluster/aws-hosted-cp/values.schema.json
- templates/cluster/aws-hosted-cp/values.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/templates/awsmachinetemplate-controlplane.yaml
- templates/cluster/aws-standalone-cp/templates/awsmachinetemplate-worker.yaml
- templates/cluster/aws-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/aws-standalone-cp/values.schema.json
- templates/cluster/aws-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/aws-eks-1-0-1.yaml
- templates/provider/kcm-templates/files/templates/aws-hosted-cp-1-0-1.yaml
- templates/provider/kcm-templates/files/templates/aws-standalone-cp-1-0-1.yaml
Added `nonRootVolumes` configuration to the AWS ClusterTemplates (standalone, EKS, hosted).
Updated JSON Schema validations to be generated along with instructions on how to do it.
Bumped the corresponding templates' versions.
Generalized the approach of the `aws-standalone-cp` to set up OIDC, preserving backward-compatibility
Fixes #1482
> feat: add non-root volumes to AWS Templates

- cmd/main.go
- internal/controller/management_controller.go
If `RegistryCertSecret` is set, add a new volume and volumeMount referencing the certificate from that secret to the CAPI operator's values.
This allows the CAPI operator to fetch provider components from the private registry signed by an unknown authority.
Also, refactor the component values overrides (all internal logic from `enableAdditionalComponents` was moved to the HelmRelease level without overwriting the Management spec, all component values overrides were moved to a single function).
Fixes #1571
> feat: Mount registry certificate secret in CAPI operator

- api/v1beta1/servicetemplate_types.go
- cmd/main.go
- internal/controller/ipam/suite_test.go
- internal/controller/servicetemplate_controller.go
- internal/controller/servicetemplate_controller_test.go
- internal/controller/suite_test.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clustertemplates.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_providertemplates.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_servicetemplates.yaml
This is the continuation of #1600 because `flux` `source-controller` API for `OCIRepository` [migrated](https://github.com/fluxcd/source-controller/blob/v1.6.0/CHANGELOG.md) from `v1beta2` to the stable `v1`
> chore: update flux source v1beta2 to v1

- api/v1beta1/clusterdeployment_types.go
- api/v1beta1/common.go
- api/v1beta1/credential_types.go
- api/v1beta1/management_types.go
- api/v1beta1/multiclusterservice_types.go
- api/v1beta1/release_types.go
- api/v1beta1/servicetemplate_types.go
- cmd/main.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/controller/template_controller.go
- internal/helm/repo.go
- internal/utils/secrets.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_credentials.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_managements.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_multiclusterservices.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_releases.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_servicetemplates.yaml
- templates/provider/kcm/templates/deployment.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
- templates/provider/kcm/values.schema.json
- templates/provider/kcm/values.yaml
Propagates k0sDownloadURL and Registry certificate Secrets to ClusterDeployments' configs.
Introduces a new condition indicating
whether all predeclared Secrets exist.
Copies the Secrets if required.
Fixes error when some of HelmRepository Secrets
might have been missed.
Checks if the given Secrets (HelmRepository and
Certificate Secrets) exist in the system namespace in each of the required controllers
(templates (all), release, management, clusterdeployment).
Fixes lax Conditions type properties.
Closes #1560
> feat: propagate registry-credentials across cld

- templates/provider/kcm/Chart.lock
- templates/provider/kcm/Chart.yaml
Continuation of https://github.com/k0rdent/kcm/pull/1600 and https://github.com/k0rdent/kcm/pull/1602.
Flux source-controller API for OCIRepository [migrated](https://github.com/fluxcd/source-controller/blob/v1.6.0/CHANGELOG.md) from v1beta2 to the stable v1 but flux 2.15.0 has OCIRepository with v1beta2 which causes the kcm-controller to fail with:
```
2025-06-06T09:16:27Z    ERROR   controller-runtime.source.Kind  if kind is a CRD, it should be installed before calling Start   {"kind": "OCIRepository.source.toolkit.fluxcd.io", "error": "no matches for kind \"OCIRepository\" in version \"source.toolkit.fluxcd.io/v1\""}
```
> chore(bump): flux helm chart 2.16.0

- internal/controller/statemanagementprovider/reconciler.go
- internal/controller/statemanagementprovider/reconciler_test.go
This PR fixes flapping unit-tests for StateManagementProvider reconciler. Test failures were caused by non-deterministic order of resources in generated RBAC rules. Aside from that `require.ElementsMatch` does not check nested slices.
- replaced `ElementsMatch` with `Equal` assertion function
- added resource list sorting before adding it to RBAC rule
Tested by:
```
❯ go test github.com/K0rdent/kcm/internal/controller/statemanagementprovider -count 1000 -failfast
ok      github.com/K0rdent/kcm/internal/controller/statemanagementprovider      4.177s
```
> test: fix flapping unit-tests for statemanagementprovider reconciler

- Makefile
Ensures unique names of support bundle archives on CI
Fixes #1636
> ci(artifacts): fix conflict in support bundles

- .github/workflows/build_test.yml
- .github/workflows/post-merge-push.yaml
- Makefile
- hack/chart-version.bash
- hack/update-dev-configs.bash
- hack/update-release.bash
Use make's yq in the scripts.
Generate templates based not only on the dirty state but rather on base commit.
Mend of #1574
> ci: amend templates scripts

- .github/workflows/post-merge-push.yaml
On merge there is no PR context nor need to change base commit for generation
> ci(merge): remove redundant base

- config/dev/gke-clusterdeployment.yaml
- templates/cluster/gcp-gke/Chart.yaml
- templates/cluster/gcp-gke/values.schema.json
- templates/cluster/gcp-gke/values.yaml
- templates/provider/kcm-templates/files/templates/gcp-gke-1-0-3.yaml
Bumps GKE Control Plane version to `1.32.4-gke.1415000` in the `gcp-gke` template
> chore(bump): gke control plane version to 1.32.4-gke.1415000

- test/e2e/clusterdeployment/constants.go
- test/e2e/clusterdeployment/gcp/env.go
- test/e2e/clusterdeployment/resources/gcp-gke.yaml.tpl
- test/e2e/clusterdeployment/resources/vsphere-standalone-cp.yaml.tpl
Adds new GKE constants to validate.
Changes GKE default channel to release, which is default as in the
template.
Changes worker resources of vsphere-standalone cld to 8CPU/8192MEM
> test: update gke and vsphere test tpls

- go.mod
- go.sum
- internal/controller/management_controller.go
- internal/controller/management_controller_test.go
- internal/controller/statemanagementprovider/reconciler_test.go
- internal/telemetry/client.go
- internal/telemetry/event.go
- internal/utils/pointer/ptr.go
- test/e2e/clusterdeployment/azure/azure.go
- test/e2e/kubevirt/vm.go
Cleans `k8s.io/utils/ptr` as a dep. Bumps `go-digest` module, along with migrating to a proper `segmentio/analytics-go` version.
> chore(tidy): cleanup some deps

- internal/sveltos/profile.go
Simple change to ensure that we provide the ca certificate for a registry when it's supplied without any client auth certificate. Fixes #1701
> fix: change logic for registry credentials for CA certs

- .github/workflows/build_test.yml
- .goreleaser.yaml
A [new goreleaser](https://github.com/goreleaser/goreleaser/releases/tag/v2.11.0) version has the required fix to conditional skip images. We do not test arm64/arm at the moment, so that reduces package amout pressure
> ci(arm): skip build in e2e tests

- templates/cluster/openstack-hosted-cp/.helmignore
- templates/cluster/openstack-hosted-cp/Chart.yaml
- templates/cluster/openstack-hosted-cp/templates/_helpers.tpl
- templates/cluster/openstack-hosted-cp/templates/cluster.yaml
- templates/cluster/openstack-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/openstack-hosted-cp/templates/k0sworkerconfigtemplate.yaml
- templates/cluster/openstack-hosted-cp/templates/machinedeployment.yaml
- templates/cluster/openstack-hosted-cp/templates/openstackcluster.yaml
- templates/cluster/openstack-hosted-cp/templates/openstackmachinetemplate.yaml
- templates/cluster/openstack-hosted-cp/values.schema.json
- templates/cluster/openstack-hosted-cp/values.yaml
- templates/provider/kcm-templates/files/templates/openstack-hosted-cp-1-0-0.yaml
This PR adds a new template for hosted OpenStack cluster deployment.
The deployment requires to provide existing network, subnet and router.
Example of the ClusterDeployment configuration:
```
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
name: ekaz-hosted
spec:
template: openstack-hosted-cp-1-1-1
credential: openstack-cluster-identity-cred
config:
clusterLabels: {}
clusterAnnotations: {}
workersNumber: 2
sshKeyName: ekaz-new
flavor: kaas.small
image:
filter:
name: ubuntu-20.04
externalNetwork:
filter:
name: "public"
authURL: https://keystone.ic-eu.ssl.mirantis.net/
identityRef:
name: "openstack-cloud-config"
cloudName: "openstack"
region: RegionOne
network:
filter:
name: …
```
> feat: Add openstack-hosted-cp template

- config/dev/remote-clusterdeployment.yaml
- templates/cluster/remote-cluster/Chart.yaml
- templates/cluster/remote-cluster/values.schema.json
- templates/cluster/remote-cluster/values.yaml
- templates/provider/kcm-templates/files/templates/remote-cluster-1-0-9.yaml
Removes validation of the machine address in the remote-cluster template.
Closes #1746
> fix: allow dns and ipv6 in remote tpl

- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/values.schema.json
- templates/provider/kcm/values.yaml
Sets velero components to fixed `velero` so the restoration would work.
Every cluster that has a version not containing the fix, still has to patch `managements` object manually before the restoration
> fix: override velero name

- config/dev/eks-clusterdeployment.yaml
- templates/cluster/aws-eks/Chart.yaml
- templates/cluster/aws-eks/values.yaml
- templates/provider/kcm-templates/files/templates/aws-eks-1-0-3.yaml
**What this PR does / why we need it**: Kubernetes version bump for `aws-aks` template
**Which issue(s) this PR fixes** _(optional, `Fixes #123`)_: Fixes #1785
> chore: Bump kubernetes to v1.32.6 in aws eks template

- config/dev/azure-clusterdeployment.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/templates/k0scontrolplane.yaml
- templates/provider/kcm-templates/files/templates/azure-hosted-cp-1-0-11.yaml
- templates/provider/kcm-templates/files/templates/azure-standalone-cp-1-0-11.yaml
More consistent images path for azure-csi images
When using custom registry image paths in that registry will be only one subpath deep and not more. By default images are under additional `/oss` subpath which breaks this rule.
> fix: azure-csi remove oss path from repository

- config/dev/gcp-clusterdeployment.yaml
- templates/cluster/gcp-hosted-cp/Chart.yaml
- templates/cluster/gcp-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/gcp-standalone-cp/Chart.yaml
- templates/cluster/gcp-standalone-cp/templates/k0scontrolplane.yaml
- templates/provider/kcm-templates/files/templates/gcp-hosted-cp-1-0-11.yaml
- templates/provider/kcm-templates/files/templates/gcp-standalone-cp-1-0-11.yaml
Fixes shadowing of node values when using global.registry
The main issue is that `kubeletPath` gets default value, because values has 2 declarations of `node` and last one has higher precedence.
> fix: gcp csi driver node values

- .goreleaser.yaml
- Makefile
**What this PR does / why we need it**: Deprecate and remove install.yaml generation
**Which issue(s) this PR fixes** _(optional, `Fixes #123`)_: Fixes #1790
> chore: Deprecate and remove install.yaml generation

- .github/actions/check-provider-in-config/action.yml
- .github/workflows/build_test.yml
Generalize check provider action to allow mixed configurations with both cloud and on-prem providers.
Added a list of on-prem providers for the generalized approach.
> ci: allow e2e tests with mixed config

- internal/controller/multiclusterservice_controller.go
- internal/sveltos/status.go
- internal/sveltos/status_test.go
Fix the `kubectl get mcs` output to:
1. Also consider SveltosCluster type alongside CAPI clusters.
2. Fix the bug where if a service errors out, the output still shows it to be deployed. E.g., if the spec has 1 service and that fails, the output still shows 1/1 services. This PR fixes this to show 0/1 services in the output.
Created the following service templates (with helm repositories):
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
name: k0rdent-catalog
labels:
k0rdent.mirantis.com/managed: "true"
spec:
insecure: true
interval: 10m0s
provider: generic
type: oci
url: oci://ghcr.io/k0rdent/catalog/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
name: nginx-upstream
labels: …
```
> fix: services deployed & clusters matched in MCS kubectl output

- templates/provider/kcm/templates/rbac/user-facing/management-editor.yaml
- templates/provider/kcm/templates/rbac/user-facing/management-viewer.yaml
This PR https://github.com/k0rdent/kcm/pull/1748 is currently missing from the `v1.2.0-release` and `main` branches. It’s being added to the `v1.2.0-release` branch to keep things in sync. The `v1.2.0-release` branch will be merged into `main` once the release is complete.
> feat: add releases to user-facing rbac (#1748)

- config/dev/remote-clusterdeployment.yaml
- templates/cluster/aws-hosted-cp/Chart.yaml
- templates/cluster/aws-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/azure-hosted-cp/Chart.yaml
- templates/cluster/azure-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/gcp-hosted-cp/Chart.yaml
- templates/cluster/gcp-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/cluster/remote-cluster/Chart.yaml
- templates/cluster/remote-cluster/templates/k0smotroncontrolplane.yaml
- templates/cluster/vsphere-hosted-cp/Chart.yaml
- templates/cluster/vsphere-hosted-cp/templates/k0smotroncontrolplane.yaml
- templates/provider/kcm-templates/files/templates/aws-hosted-cp-1-0-12.yaml
- templates/provider/kcm-templates/files/templates/azure-hosted-cp-1-0-13.yaml
- templates/provider/kcm-templates/files/templates/gcp-hosted-cp-1-0-13.yaml
- templates/provider/kcm-templates/files/templates/remote-cluster-1-0-12.yaml
- templates/provider/kcm-templates/files/templates/vsphere-hosted-cp-1-0-11.yaml
**What this PR does / why we need it**: 
Cherry-pick of https://github.com/k0rdent/kcm/commit/4e6f000a5526b55bf37c26b6f17db506c2acd823 to fix konnectivity image path when using a custom registry.
> fix: konnectivity image for hosted templates; bump chart versions

- cmd/main.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/management_controller.go
- internal/controller/release_controller.go
- internal/helm/release.go
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/templates/deployment.yaml
- templates/provider/kcm/values.schema.json
- templates/provider/kcm/values.yaml
This PR allows the configuration of the default timeout for HelmReleases. If not specified, the default Flux's value will be used (5 minutes).
Fixes #1643
> fix: allow configuration of the default HelmRelease timeout

- api/v1beta1/multiclusterservice_types.go
- api/v1beta1/zz_generated.deepcopy.go
- internal/controller/multiclusterservice_controller.go
- internal/utils/validation/cd.go
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clusterdeployments.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_multiclusterservices.yaml
Exposing `services.policyRef` field in CD and MCS spec in order to support features like propagating secrets from k0rdent management cluster to target cluster. See https://github.com/k0rdent/catalog/pull/503.
I have the following secret:
```sh
➜  ~ kubectl -n kcm-system get secret secret-dockercfg 
NAME               TYPE                      DATA   AGE
secret-dockercfg   kubernetes.io/dockercfg   1      27h
```
And I want to propagate it to the following target cluster in "myns" namespace:
```sh
➜  ~ kubectl -n kcm-system get cluster --show-labels 
NAME         CLUSTERCLASS   PHASE         AGE   VERSION   LABELS
wali-dev-1                  Provisioned   28h             app.kubernetes.io/managed-by=Helm,helm.toolkit.fluxcd.io/name=wali-dev-1,helm.toolkit.fluxcd.io/namespace=kcm-system,k0rd …
```
> feat: expose services.policyRef in CD and MCS spec 

- internal/controller/management_controller.go
- internal/helm/repo.go
`certSecretRef` in flux HelmRepository does not work properly when using a registry with redirects. To workaround it, we need to mount the CA cert secret as a volume to helm and source controllers.
Fixes #1841
> fix: Mount CA cert as a volume to flux components

- internal/controller/management_controller.go
- internal/controller/release_controller.go
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/templates/rbac/controller/roles.yaml
This is the fix for the Flux issue to ensure that the registry CA certificate is mounted into the Flux source controller deployment before attempting to pull `kcm-templates` chart from a private registry. Without the certificate in place early, the `kcm-templates` installation fails on:
```
- lastTransitionTime: "2025-08-08T21:08:06Z"
message: 'HelmChart ''k0rdent/kcm-1-1-0-rc14-tpl'' is not ready: chart pull error:
failed to download chart for remote reference: failed to get ''oci://registry.mke4dev.miratnis.com/mke/charts/kcm-templates:1.1.0-rc14'':
failed to do request: Head "https://registry.mke4dev.miratnis.com/v2/mke/charts/kcm-templates/manifests/1.1.0-rc14":
tls: failed to verify certificate: x509: certificate signed by unknown authority' …
```
> fix: Mount CA secret to flux before installing kcm-templates

- test/e2e/clusterdeployment/azure/azure.go
- test/e2e/config/config.go
- test/e2e/e2e_suite_test.go
- test/e2e/kubeclient/kubeclient.go
- test/e2e/logs/logs.go
- test/e2e/multi_provider_test.go
- test/e2e/provider_adopted_test.go
- test/e2e/provider_aws_test.go
- test/e2e/provider_azure_test.go
- test/e2e/provider_gcp_test.go
- test/e2e/provider_remote_test.go
- test/e2e/provider_vsphere_test.go
* Always write the cluster kubeconfig before collecting the support dump
* Apply default e2e provider config if nothing is provided
* Several small fixes
**Which issue(s) this PR fixes** _(optional, `Fixes #123`)_: 
Fixes #1812
> test: fix support dump collecting

- config/dev/remote-clusterdeployment.yaml
- templates/cluster/remote-cluster/Chart.yaml
- templates/cluster/remote-cluster/templates/machines.yaml
- templates/provider/kcm-templates/files/templates/remote-cluster-1-0-13.yaml
The remote-cluster template now respects per-machine .useSudo parameter.
Fixes #1879
> fix: remote-cluster (hosted) respects useSudo

- config/dev/aws-clusterdeployment.yaml
- config/dev/azure-clusterdeployment.yaml
- config/dev/gcp-clusterdeployment.yaml
- config/dev/openstack-clusterdeployment.yaml
- config/dev/vsphere-clusterdeployment.yaml
- templates/cluster/aws-standalone-cp/Chart.yaml
- templates/cluster/aws-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/aws-standalone-cp/values.schema.json
- templates/cluster/aws-standalone-cp/values.yaml
- templates/cluster/azure-standalone-cp/Chart.yaml
- templates/cluster/azure-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/azure-standalone-cp/values.schema.json
- templates/cluster/azure-standalone-cp/values.yaml
- templates/cluster/gcp-standalone-cp/Chart.yaml
- templates/cluster/gcp-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/gcp-standalone-cp/values.schema.json
- templates/cluster/gcp-standalone-cp/values.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/openstack-standalone-cp/values.schema.json
- templates/cluster/openstack-standalone-cp/values.yaml
- templates/cluster/vsphere-standalone-cp/Chart.yaml
- templates/cluster/vsphere-standalone-cp/templates/k0scontrolplane.yaml
- templates/cluster/vsphere-standalone-cp/values.schema.json
- templates/cluster/vsphere-standalone-cp/values.yaml
- templates/provider/kcm-templates/files/templates/aws-standalone-cp-1-0-13.yaml
- templates/provider/kcm-templates/files/templates/azure-standalone-cp-1-0-14.yaml
- templates/provider/kcm-templates/files/templates/gcp-standalone-cp-1-0-13.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-1-0-15.yaml
- templates/provider/kcm-templates/files/templates/vsphere-standalone-cp-1-0-12.yaml
Allows for more simple network configuration ergonomics when  building custom ClusterTemplate charts. Configuring networks is an extremely common use case. So we should make this as simple as possible.
Fixes #1873
> fix: moved network configuration for standalone charts into values.yaml

- internal/controller/multiclusterservice_controller.go
This PR fixes MultiClusterService requeue when no changes were made during reconciliation. This is needed to not to miss clusterDeployments with labels matching defined selector.
> fix: multiclusterservice requeue

- config/dev/openstack-clusterdeployment.yaml
- templates/cluster/openstack-hosted-cp/Chart.yaml
- templates/cluster/openstack-hosted-cp/templates/openstackmachinetemplate.yaml
- templates/cluster/openstack-standalone-cp/Chart.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-controlplane.yaml
- templates/cluster/openstack-standalone-cp/templates/openstackmachinetemplate-worker.yaml
- templates/provider/kcm-templates/files/templates/openstack-hosted-cp-1-0-5.yaml
- templates/provider/kcm-templates/files/templates/openstack-standalone-cp-1-0-15.yaml
https://github.com/k0rdent/kcm/pull/1794 introduced `clusterIdentity` but missed replacing the old values in the machine templates. This PR addresses it
> fix(os-tpls): correct identity name in identityref

- .gitignore
- go.mod
- go.sum
- templates/provider/cluster-api-provider-infoblox/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/cluster-api-provider-infoblox.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/provider_aws_test.go
- test/e2e/provider_azure_test.go
- test/e2e/provider_gcp_test.go
- test/e2e/provider_vsphere_test.go
Bumps infoblox to v0.1.0 with arm64 support.
Removes kludge in e2e tests.
Closes #1885
> fix(infoblox): support arm64

- api/v1beta1/templates_common.go
- internal/controller/template_controller.go
- internal/controller/template_controller_test.go
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_clustertemplates.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_providertemplates.yaml
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_servicetemplates.yaml
Added the `schemaConfigMapName` field to the template’s status and enabled the generation of the ConfigMap. If the referenced Helm chart includes values.schema.json (as it normally should), the schema will be available in the ConfigMap.
Resolves: #1839
> feat: add JSON Schema configmap for templates if available

- api/v1beta1/region_types.go
- internal/controller/components/reconciler.go
- internal/controller/region/controller.go
- internal/helm/release.go
- templates/provider/kcm/templates/crds/k0rdent.mirantis.com_regions.yaml
1. Add Ready and Age printcolumns to Region objects.
2. Ensure the Ready condition is updated correctly for Region objects.
3. Do not prefix regional releases with the region name. Previously helm releases were installed with a name that equals the HelmRelease object name. With this change, the new field (ReleaseName) was introduced to the `ReconcileHelmReleaseOpts` that allows overriding the name of the deployed helm release. It's needed to avoid an unnecessary prefix for all the regional helm releases.
Related task #1979
> feat: several minor Region improvements

- api/v1beta1/region_types.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/components/values.go
- internal/controller/credential_controller.go
- internal/controller/region/controller.go
- internal/controller/template_controller.go
- internal/utils/secrets.go
When k0rdent was deployed with the custom registry and/or k0s URL and with the `registryCertSecret` or `k0sURLCertSecret` defined, the certificate secrets should be present in the mothership cluster. In case the cluster is deployed in the region, the certificates' secrets are copied to the regional cluster.
Additionally, this PR contains several fixes: 
1. `cluster-api-operator`, `velero`, and `cert-manager` configuration was moved to the `regional` section of the `kcm` helm chart. To support backward compatibility, the values of these components are still retrieved from these sections.
2.  Credential now contains an error if it fails to get the regional client (ex. if the region is not found).
3. While copying the certificate to the child cluster …
> feat: copy certificate secrets to regional clusters

- config/dev/kcm_values.yaml
Increase the default Helm install/upgrade timeout to 20 minutes to account for slow network.
> fix: increase default helm timeout for dev setup

- api/v1beta1/indexers.go
- cmd/main.go
- internal/controller/adapters/sveltos/serviceset_controller.go
- internal/controller/clusterdeployment_controller.go
- internal/controller/credential_controller.go
- internal/controller/region/client.go
- internal/controller/region/controller.go
- internal/utils/scheme/scheme.go
- internal/utils/validation/cd.go
* Use the regional client to access sveltos objects.
* Do not allow removal of ClusterDeployment until all ServiceSets are removed.
* Since kcm controller can't watch regional sveltos objects (profile, clustersummary), requeue the reconciler until the service is deployed.
* Refactor scheme getter functions.
Relates to #1979
> feat: adapt services reconciliation to regional clusters

- README.md
- templates/provider/kcm-templates/Chart.yaml
- templates/provider/kcm-templates/files/release.yaml
- templates/provider/kcm-templates/files/templates/kcm.yaml
- templates/provider/kcm/Chart.yaml
Sets `1.4.0` version in all objects/README to avoid confusion
> chore: post-release 1.4.0 version set
